### ISSUE TITLE
Can mars do df.query() method like pandas?

### ISSUE THREAD

**Issue by kerwin6182828** [mars-project/mars#1219]
i'm used to doing df.query() in pandas. and now , i just know mars can calculate data as well as pandas, or even better.
but i didn't find query() method. is these in the plan？

**Comment by qinxuye** [comment]
OK, we will do some investigation, and see when it can be implemented in Mars.

**Comment by qinxuye** [comment]
`df.query` has been implemented, and will be included in v0.7.0a5 as well as v0.6.4, however, you can choose to build from source code on your own.
