### ISSUE TITLE
[BUG] As there are no _tensor_to_tiled in GraphActor, referencing it will lead to AttributeError

### ISSUE THREAD

**Issue by wjsi** [mars-project/mars#124]
**Describe the bug**
As there are no _tensor_to_tiled in GraphActor, referencing it in https://github.com/mars-project/mars/blob/9e4942c308a60d488893391114d5383ae319e206/mars/scheduler/graph.py#L773 will lead to AttributeError

**Expected behavior**
Use _get_tensor_by_key() instead. Cases are also recommended. Currently the line https://coveralls.io/builds/21024102/source?filename=mars/scheduler/graph.py#L773 is not covered.

**Comment by chineking** [comment]
Introduced by #120 , mainly because the tests are mock patched, and not covered, hope this could be resolved after fix on #117 .
