### ISSUE TITLE
DataFrameGroupBy missing size() method.

### ISSUE THREAD

**Issue by jkryanchou** [mars-project/mars#1245]
**Is your feature request related to a problem? Please describe.**

I have processed a amount of data which read from 'md.read_csv()' method and got the DataFrameGroupBy object by invoking `groupby()` method. While it could not chain the `size()` method as `Pandas` do.

I wish repo-maintainers could add more feature on Mars to keep API be consistent with Pandas.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Mars should consider that support more sql-like functions on DataFrame in order to migrate SQL users could make use of Mars to empower their workflow.

https://medium.com/jbennetcodes/how-to-rewrite-your-sql-queries-in-pandas-and-more-149d341fc53e

**Comment by wjsi** [comment]
We will add this method in the next release. btw, you can use ``df.groupby('key').apply(lambda df: len(df))`` to compute the result of ``df.groupby('key').size()``.
