### ISSUE TITLE
Cannot set columns for Mars DataFrame

### ISSUE THREAD

**Issue by We1less1111** [mars-project/mars#1305]
How to rename a column？pd.columns = ['a','b','c'], **error**

**Comment by qinxuye** [comment]
Oh, it's not supported in Mars DataFrame yet, I will support it ASAP.

**Comment by We1less1111** [comment]
> Oh, it's not supported in Mars DataFrame yet, we will implement it ASAP.

The foolish idea is as follows，What is the impact on Performance？？  Thanks
data = data.to_pandas()
data.columns = ['a','b','c','d']
data= pd.DataFrame(data)

**Comment by qinxuye** [comment]
> > Oh, it's not supported in Mars DataFrame yet, we will implement it ASAP.
> 
> The foolish idea is as follows，What is the impact on Performance？？ Thanks
> data = data.to_pandas()
> data.columns = ['a','b','c','d']
> data= pd.DataFrame(data)

I think the performance could be terrible, because the data will be collected together.

This feature can be easily achieved for Mars, we will finish it in a few days, and you would be able to set columns in the next release 0.4.2 around Jun 24.

**Comment by qinxuye** [comment]
v0.4.2 has been released. Fixes about this issue have been included.

Try to upgrade via:

```
pip install pymars==0.4.2
```
