### ISSUE TITLE
[BUG] Failed when groupby takes 3 params

### ISSUE THREAD

**Issue by We1less1111** [mars-project/mars#1308]
1、when groupby take 2 params, it‘s ok 

> callOutData =data_drop.groupby(['callingMSISDN','calledMSISDN']).size().reset_index(name='size')
> callOutData.execute()

 result: 

> callingMSISDN | calledMSISDN | size
> 0 | 13420253528 | 13824722080 | 2
> 1 | 13564811632 | 15665088515 | 1

2、when groupby take 3 params,it's terrible

> callOutData =data_drop.groupby(['callingMSISDN','midGroupId','calledMSISDN']).size().reset_index()
> callOutData.execute()

errr_esult:

> ValueError: Length of names must match number of levels in MultiIndex.

**Comment by qinxuye** [comment]
For the failed case, could you please paste the full error stack as well as the code?

**Comment by We1less1111** [comment]
code:
> print(data_drop.columns.execute())
> callOutData = data_drop.groupby(['callingMSISDN','midGroupId','calledMSISDN']).size().reset_index()
> callOutData.execute()

result:

> Index(['callingMSISDN', 'midGroupId', 'calledMSISDN'], dtype='object')
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-11-3b9912da31f6> in <module>
>       1 print(data_drop.columns.execute())
> ----> 2 callOutData = data_drop.groupby(['callingMSISDN','midGroupId','calledMSISDN']).size().reset_index()
>       3 callOutData.execute()
> 
> D:\kinggsoft\anaconda\lib\site-packages\mars\dataframe\base\reset_index.py in series_reset_index(series, level, drop, name)
>     209 def series_reset_index(series, level=None, drop=False, name=None):
>     210     op = DataFrameResetIndex(level=level, drop=drop, name=name, object_type=ObjectType.series)
> --> 211     return op(series)
> 
> D:\kinggsoft\anaconda\lib\site-packages\mars\dataframe\base\reset_index.py in __call__(self, a)
>     198             return self._call_dataframe(a)
>     199         else:
> --> 200             return self._call_series(a)
>     201 
>     202 
> 
> D:\kinggsoft\anaconda\lib\site-packages\mars\dataframe\base\reset_index.py in _call_series(self, a)
>     168         else:
>     169             self._object_type = ObjectType.dataframe
> --> 170             empty_series = build_empty_series(dtype=a.dtype, index=a.index_value.to_pandas()[:0], name=a.name)
>     171             empty_df = empty_series.reset_index(level=self.level, name=self.name)
>     172             shape = (a.shape[0], len(empty_df.dtypes))
> 
> D:\kinggsoft\anaconda\lib\site-packages\mars\dataframe\core.py in to_pandas(self)
>     276 
>     277     def to_pandas(self):
> --> 278         return self._index_value.to_pandas()
>     279 
>     280     @classmethod
> 
> D:\kinggsoft\anaconda\lib\site-packages\mars\dataframe\core.py in to_pandas(self)
>     190             if data is None:
>     191                 return pd.MultiIndex.from_arrays([[], []], sortorder=self._sortorder,
> --> 192                                                  names=self._names)
>     193             return pd.MultiIndex.from_tuples([tuple(d) for d in data], sortorder=self._sortorder,
>     194                                              names=self._names)
> 
> D:\kinggsoft\anaconda\lib\site-packages\pandas\core\indexes\multi.py in from_arrays(cls, arrays, sortorder, names)
>     427             sortorder=sortorder,
>     428             names=names,
> --> 429             verify_integrity=False,
>     430         )
>     431 
> 
> D:\kinggsoft\anaconda\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
>     206                 else:
>     207                     kwargs[new_arg_name] = new_arg_value
> --> 208             return func(*args, **kwargs)
>     209 
>     210         return wrapper
> 
> D:\kinggsoft\anaconda\lib\site-packages\pandas\core\indexes\multi.py in __new__(cls, levels, codes, sortorder, names, dtype, copy, name, verify_integrity, _set_identity)
>     262         if names is not None:
>     263             # handles name validation
> --> 264             result._set_names(names)
>     265 
>     266         if sortorder is not None:
> 
> D:\kinggsoft\anaconda\lib\site-packages\pandas\core\indexes\multi.py in _set_names(self, names, level, validate)
>    1223         if validate and level is None and len(names) != self.nlevels:
>    1224             raise ValueError(
> -> 1225                 "Length of names must match number of levels in " "MultiIndex."
>    1226             )
>    1227 
> 
> ValueError: Length of names must match number of levels in MultiIndex.

**Comment by qinxuye** [comment]
Thanks, we will try to reproduce the error, and fix it ASAP.

**Comment by qinxuye** [comment]
v0.4.2 has been released. Fixes about this issue have been included.

Try to upgrade via:

```
pip install pymars==0.4.2
```
