### ISSUE TITLE
[BUG] Compare Series and datetime failed

### ISSUE THREAD

**Issue by ztsweet** [mars-project/mars#1313]
Compare Series and datetime failed, the sample code:

![error](https://user-images.githubusercontent.com/47625450/85000057-7aaa4500-b184-11ea-873b-14b052e2af85.png)

**Comment by qinxuye** [comment]
Setting columns is mentioned in #1305 .

About comparison between Series and datetime, we will fix it ASAP.

**Comment by qinxuye** [comment]
v0.4.2 has been released. Fixes about this issue have been included.

Try to upgrade via:

```
pip install pymars==0.4.2
```

**Comment by ztsweet** [comment]
Suggestion: It's better to keep the symbols consistent（mars.dataframe & pandas），and mark the places where the results are wrong。
![datetime](https://user-images.githubusercontent.com/47625450/85370947-19a6b680-b562-11ea-88c6-525cb7237be9.png)

**Comment by qinxuye** [comment]
> Suggestion: It's better to keep the symbols consistent（mars.dataframe & pandas），and mark the places where the results are wrong。
> ![datetime](https://user-images.githubusercontent.com/47625450/85370947-19a6b680-b562-11ea-88c6-525cb7237be9.png)

Could you please open a new issue to describe the new problem?
