### ISSUE TITLE
[BUG] Fail to read TiDB via MySQL connection

### ISSUE THREAD

**Issue by ztsweet** [mars-project/mars#1334]
![sqlbug](https://user-images.githubusercontent.com/47625450/85351003-3f699680-b535-11ea-86b8-f775454322d1.png)

**Comment by wjsi** [comment]
In read_sql_query we use ``WHERE 1=0`` to detect the schema of the input query, which is also the practice of ``spark.read.jdbc`` while TiDB does not support it. We are considering how to make a workaround.

**Comment by ztsweet** [comment]
Sqlalchemy is supported in the parameter specification
![sqlalchemy](https://user-images.githubusercontent.com/47625450/85371548-faf4ef80-b562-11ea-971a-2ea540a6be5e.png)
