### ISSUE TITLE
Support DataFrame.assign

### ISSUE THREAD

**Issue by wjsi** [mars-project/mars#1336]
Support DataFrame.assign. pandas docs see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.assign.html .

**Comment by gowrijsuria** [comment]
Hi, 
Can I work on this for my first issue?

**Comment by qinxuye** [comment]
> Hi,
> Can I work on this for my first issue?

Sure, fork & send a PR :)

**Comment by gowrijsuria** [comment]
Is there any similar example in the current codebase that I can follow?

**Comment by qinxuye** [comment]
> Is there any similar example in the current codebase that I can follow?

Since Mars DataFrame already support `__setitem__`, so basically what you need to do is to add an `assign` function to 

https://github.com/mars-project/mars/blob/0c9114d1fffe56af7e3a3da01c7534e9597237a2/mars/dataframe/core.py#L1599

in which `__setitem__` can be used.
