### ISSUE TITLE
[BUG] Worker could not be started as described in the README

### ISSUE THREAD

**Issue by pingrunhuang** [mars-project/mars#140]
**Describe the bug**
As described in the README.md file, worker process should be started properly after I started the `scheduler` and `web` process. However, after the `scheduler` and `web` are spawned which went well for both, the worker process fall into the following issue:

![screen shot 2019-01-17 at 4 14 46 pm](https://user-images.githubusercontent.com/13326067/51305020-a481a880-1a74-11e9-8bf0-7e78a742ae9b.png)

One thing to note is that I run it on a docker container as I want to separate the environment from the system environment. And I also strongly recommend adding Dockerfile and docker-compose.yml file to this project. I have already created these 2 files which is ready to be tested. If you want I can create a pull request.

1. Your Python version: `python 3.7.1`
2. The version of Mars you use: `'0.1.0b1'`
3. Versions of crucial packages, such as numpy, scipy and protobuf:
```
bokeh            1.0.4     
certifi          2018.11.29
chardet          3.0.4     
dnspython        1.16.0    
etcd-gevent      0.1.1     
gevent           1.4.0     
geventhttpclient 1.3.1     
greenlet         0.4.15    
idna             2.8       
Jinja2           2.10      
lz4              2.1.6     
MarkupSafe       1.1.0     
numexpr          2.6.9     
numpy            1.16.0    
packaging        18.0      
pandas           0.23.4    
Pillow           5.4.1     
pip              18.1      
protobuf         3.6.1     
psutil           5.4.8     
pyarrow          0.11.1    
pymars           0.1.0b1   
pyparsing        2.3.1     
python-dateutil  2.7.5     
pytz             2018.9    
PyYAML           3.13      
requests         2.21.0    
scipy            1.2.0     
setuptools       40.6.2    
six              1.12.0    
tornado          5.1.1     
urllib3          1.24.1    
wheel            0.32.2  
```
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Expected behavior**
Start properly

**Comment by pingrunhuang** [comment]
I imagine either the `--endpoint` should be specified or somehow I did it wrong.

**Comment by NJUPole** [comment]
> I imagine either the `--endpoint` should be specified or somehow I did it wrong.

It's a bug, you can specified `--cache-mem 45%` as a workaround.

**Comment by NJUPole** [comment]
> And I also strongly recommend adding Dockerfile and docker-compose.yml file to this project. I have already created these 2 files which is ready to be tested. If you want I can create a pull request.

Thanks for your advice, you can open an issue firstly and then pull request, contribution is always welcome!

**Comment by pingrunhuang** [comment]
1. Adding `--cache-mem 45%` does not solve the issue which raise another error caused by the `pyarrow`.
```
Traceback (most recent call last):
  File "/usr/local/bin/mars-worker", line 20, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/mars/base_app.py", line 71, in __call__
    return self._main(new_argv)
  File "/usr/local/lib/python3.7/site-packages/mars/base_app.py", line 127, in _main
    self.endpoint, self.pool = self._try_create_pool(endpoint=endpoint, host=host, port=port)
  File "/usr/local/lib/python3.7/site-packages/mars/base_app.py", line 161, in _try_create_pool
    pool = self.create_pool(address=endpoint)
  File "/usr/local/lib/python3.7/site-packages/mars/worker/__main__.py", line 85, in create_pool
    one_mapped_file=options.worker.plasma_one_mapped_file or False)
  File "/usr/local/lib/python3.7/site-packages/mars/worker/service.py", line 70, in start_plasma
    options.worker.plasma_socket, _ = self._plasma_store.__enter__()
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/pyarrow/plasma.py", line 138, in start_plasma_store
    "code %d" % (rc,))
RuntimeError: plasma_store exited unexpectedly with code -6
```
I think it is not essentially a solution. 
2. 

> Thanks for your advice, you can open an issue firstly and then pull request, contribution is always welcome!
Yeah sure, I will create it later!

**Comment by wjsi** [comment]
> Adding --cache-mem 45% does not solve the issue which raise another error caused by the pyarrow.
Mars uses ``plasma-store`` as shared memory container, which relies on free space on free memory on current machine. Therefore if the specified memory size exceeds free memory, ``plasma_store`` will fail. The resolution is to set a fixed size, for instance, ``1g``, for the storage. We will consider a simpler configuration in the next release. What's more, 
> mars-worker -a <worker_ip> -p <worker_port> -s <scheduler_ip>
is a typo, which should be
> mars-worker -a <worker_ip> -p <worker_port> -s <scheduler_endpoint>
We apologize for those inconveniences and promise that these bugs will be fixed as soon as possible.

**Comment by pingrunhuang** [comment]
> > Adding --cache-mem 45% does not solve the issue which raise another error caused by the pyarrow.
> 
> Mars uses `plasma-store` as shared memory container, which relies on free space on free memory on current machine. Therefore if the specified memory size exceeds free memory, `plasma_store` will fail. The resolution is to set a fixed size, for instance, `1g`, for the storage. We will consider a simpler configuration in the next release. What's more,
> 
> > mars-worker -a <worker_ip> -p <worker_port> -s <scheduler_ip>
> 
> is a typo, which should be
> 
> > mars-worker -a <worker_ip> -p <worker_port> -s <scheduler_endpoint>
> 
> and the same mistake occurs on the description of `mars-web` command.
> 
> We apologize for those inconveniences and promise that these bugs will be fixed as soon as possible.

**Comment by wjsi** [comment]
@pingrunhuang You may keep this issue open till we fix it. :-)

**Comment by pingrunhuang** [comment]
@wjsi Btw, could you give an example in the readme to better illustrate how to access the cluster? Can I just define any endpoint without any other changes in the code?

**Comment by chineking** [comment]
> @wjsi Btw, could you give an example in the readme to better illustrate how to access the cluster? Can I just define any endpoint without any other changes in the code?

Create a session, and set it as default is a quick way.

```python
from mars.session import new_session

endpoint = '***'
# create a session
new_session(endpoint).as_default()

a = ***
a.sum().execute()  # will run on the cluster
```

**Comment by pingrunhuang** [comment]
@chineking I mean what should the endpoint look like. I need this to create a compose file for those who want to just start a simple cluster and run code on it.

**Comment by chineking** [comment]
> @chineking I mean what should the endpoint look like. I need this to create a compose file for those who want to just start a simple cluster and run code on it.

It's the web's address, sth like `http://<web_ip>:<web_port>`.

**Comment by wjsi** [comment]
As I just tested the latest master on our cluster and it turns out to be OK, I decide to close this. Feel free to reopen if the same problem occurs again.
