### ISSUE TITLE
[BUG] ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by jingyan6** [mars-project/mars#1443]
df_result = md.concat([df_result, df_res])
df_result.to_csv('bad.csv').execute()
两个dareframe  concat 后导出报错 
    itemsize = max(dt.itemsize for dt in a.dtypes)
ValueError: max() arg is an empty sequence

**Comment by qinxuye** [comment]
Could you please paste minimal sample code including how to create `df_result` as well as `df_res` to help us more simpler to reproduce the error, full error stack is welcomed to help us to figure out the error originates from.

**Comment by wjsi** [comment]
Close as no additional information given, thus the context of the error can not be inspected. Feel free to reopen it if the same error appear again and details can be provided.
