### ISSUE TITLE
How to do groupby then aggregate with nunique

### ISSUE THREAD

**Issue by qinglok** [mars-project/mars#1467]
`df.groupby(['a', 'b']).agg({
        {'c': 'nunique'}: 'count'
    }).execute()`
这样写跑不起来。
想要实现的效果类似这样的SQL
`select a, b, count( distinct c ) from t group by a, c`

**Comment by qinxuye** [comment]
`nunique` is unique+count, I guess what you need is just `nunique`.

**Comment by hekaisheng** [comment]
Try `df.groupby(['A', 'B']).agg({'C': 'nunique'}).execute()`.

**Comment by wjsi** [comment]
Duplicate with #1124
