### ISSUE TITLE
Add docker-compose.yml for starting cluster

### ISSUE THREAD

**Issue by pingrunhuang** [mars-project/mars#147]
**Is your feature request related to a problem? Please describe.**
related to issue #146 

**Describe the solution you'd like**
Convenient for quick start cluster.

**Comment by wjsi** [comment]
So is it just an example on Docker Swarm? We already have [local cluster](https://mars-project.readthedocs.io/en/latest/install.html#local-cluster) mode on a standalone machine, and when deploying on distributed deployments, Kubernetes are used more frequently.
What's more, when people starts their clusters, there are often different needs on scheduler and worker counts, whether to use etcd or redis, memory configuration, data sizes, spill locations and so on. I wonder how far a single ``docker-compose.yml`` can reach.

**Comment by pingrunhuang** [comment]
@wjsi From the user's perspective, I tried followed the instruction of [here](https://mars-project.readthedocs.io/en/latest/install.html#run-on-clusters). But turns out the system environment (Running on Mac OS) somehow could not manage to start the scheduler, worker and web. I understand Kubernetes is a production need, but still I think there should have some kind of standard way of spawning up cluster. At least for me, the `Run on cluster` does not work. So I think either make a compose file or have a more specific instruction to fit in different users.

**Comment by wjsi** [comment]
This will be solved in our next beta which will be released in days, and it has already been merged into v0.1 branch (#143). It is unwise trying to solve one problem by introducing an irrelevant one.

**Comment by pingrunhuang** [comment]
@wjsi Personally I don't agree `It is unwise trying to solve one problem by introducing an irrelevant one.` Cause as a user perspective, at least a runnable quick start should be tested in different operating system. Simply writing `mars-web -a <web_ip> -s <scheduler_ip> --ui-port <ui_port_exposed_to_user>` is not user-friendly. A more specific instruction and platform independent solution should be stated. Anyway, it is totally understandable if you don't accept this solution based on this project's consideration.

**Comment by wjsi** [comment]
I don't think there is any difference between writing ``mars-web args`` and ``docker run -v dira:dirb mars-web args`` if everything is ok. The problem on MacOS ```is a bug that can happen on every platform`` and we've already solve it. Therefore trying to tackle on platform compatibility is obviously irrelevant.
