### ISSUE TITLE
[BUG]The local distributed mode don't work

### ISSUE THREAD

**Issue by windsparrow** [mars-project/mars#1471]
**Describe the bug**
I just run the code in "mars-example/Welcome.ipynb", but it didn't work.

I think it should have been a basic feature.

**To Reproduce**
Just run the following code , after seconds of high cpu usage rate, the cpu wounld fall silient (almost total idle), and the resual also wouldn't come out.

'''
from mars.config import options
from mars import tensor as mt
from mars.session import new_session
from mars.deploy.local.core import LocalDistributedCluster

endpoint='0.0.0.0:12345'
options.worker.cache_memory_limit = '4G'
with LocalDistributedCluster(endpoint) as cluster:
    with new_session(endpoint) as session:
        N = 10 ** 7
        data = mt.random.uniform(-1, 1, size=(N, 2))
        inside = (mt.linalg.norm(data, axis=1) < 1).sum()
        pi = 4 * inside / N
        result = session.run(pi)
        print('pi: %.5f' % result)
'''
This is the state of my cpu:
![image](https://user-images.githubusercontent.com/3444719/89722374-7a5b5700-da1b-11ea-91c0-004e8849ded3.png)

**Expected behavior**
1.Result would come out
2.All cpus cores would run in high speed

**Comment by wjsi** [comment]
The mars-example repository is fairly old and may not agree with current version of Mars. We may decide whether to update or deprecate it recently. 90% of execution stuck is caused by insufficient resources. We will handle it in #1472.

Starting local clusters are simpler in the latest Mars release. Just use

```
import mars.tensor as mt
from mars.deploy.local import new_cluster                                                                     

cluster = new_cluster()  # This will automatically create a session and set it as default
N = 10 ** 7
data = mt.random.uniform(-1, 1, size=(N, 2))
inside = (mt.linalg.norm(data, axis=1)<1).sum()
pi = 4 * inside / N
pi.execute()  # returns 3.1416696 on my laptop
```

**Comment by windsparrow** [comment]
Thanks a lot, and I will try.
And also I think mars is realy great, maybe you should give more docs to the publics.
It will make influence.

**Comment by wjsi** [comment]
Close as no further messages. ``mars-examples`` repo has been closed temporarily.
