### ISSUE TITLE
Provide a way to start a complete distributed environment in a single machine

### ISSUE THREAD

**Issue by chineking** [mars-project/mars#16]
**Is your feature request related to a problem? Please describe.**

Now it's quite painful to start a complete distributed environment in a single machine, we have to start the scheduler, start the worker, then start the web.

**Describe the solution you'd like**

I hope there is a simple way to do this by a single line of code. For example

```
from mars.deploy.local import new_cluster

cluster = new_cluster()
```

and then we can create a session by

```
from mars.session import new_session

session = new_session(cluster.endpoint)
```

Of course this is just an example.

**Describe alternatives you've considered**

I suggest we start the scheduler and worker in an actor pool, and start the web in a separate process.

**Additional context**

It's also useful for using in our unittests.

**Comment by chineking** [comment]
I will take over this job.

When I try to fix the #8 ，the serialization issue is resolved, but under the distributed setting, there's still problem which leads to a hang at the client side, I think after the implementation of pseudo-distributed mode, it's simpler to discover the real problem under the hood.

**Comment by lyman** [comment]
a cluster class manages a web process, a scheduler process and several worker processes?

seems easy enough, I can give it a try

**Comment by chineking** [comment]
Yeah, mars.deploy.local.new_cluster will start a service bundled with scheduler, worker and web.

I am working on it. Perhaps one or two days later can have a try.
