### ISSUE TITLE
`dataframe.index` needs to add  attribute  like `name` of the index

### ISSUE THREAD

**Issue by fengwuyun** [mars-project/mars#1665]
**Describe the solution you'd like**

I find it hard to change the name of  index of dataframes when I use mars. Compared to mars, you can change the name by the following ways:

```python
df.index.name = "_id" #this way means inplace=True; single-level index
df.index.names = ["_id"] # multi-level index
```
or
```python
df.index.set_names(['foo'],inplace=True)
```
With it, I can change the name of single-level index and multi-level index more convenient.

**Comment by qinxuye** [comment]
Thanks, we will add support ASAP.
