### ISSUE TITLE
[BUG] AttributeError when calling read_parquet('xxx.parquet')

### ISSUE THREAD

**Issue by wangxin0716** [mars-project/mars#1695]
I tried to call `read_parquet` to read a parquet file generated by `pandas.to_parquet()`. The file could be successfully read by `pandas.read_parquet()`. But when I tried to call `mars.dataframe.read_parquet` on it, I got the following error:

> /opt/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/mars/dataframe/datasource/read_parquet.py in read_parquet(path, engine, columns, groups_as_chunks, use_arrow_dtype, incremental_index, storage_options, **kwargs)

    393 
    394         with open_file(file_path, storage_options=storage_options) as f:
    395             dtypes = engine.read_dtypes(f)
    396 
    397         if columns:

> /opt/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/mars/dataframe/datasource/read_parquet.py in read_dtypes(self, f, **kwargs)
     88     def read_dtypes(self, f, **kwargs):
     89         file = pq.ParquetFile(f)
     90         return file.schema_arrow.empty_table().to_pandas().dtypes
     91 
     92     @classmethod

AttributeError: 'ParquetFile' object has no attribute 'schema_arrow'

What could the problem be?

**Comment by hekaisheng** [comment]
Could you please run `import pyarrow; print(pyarrow.__version__)` to print the pyarrow version?

**Comment by wangxin0716** [comment]
The pyarrow version is `0.16.0`, and the pymars version is `0.5.3`.

**Comment by hekaisheng** [comment]
Could you upgrade your pyarrow to 0.17.0 or later and run your code again?

**Comment by wangxin0716** [comment]
I upgrade pyarrow to `2.0.0`, then the problem disappears. Thank you very much.

**Comment by hekaisheng** [comment]
> I upgrade pyarrow to `2.0.0`, then the problem disappears. Thank you very much.

Thank your report, we will add a hint in our error message.

**Comment by hekaisheng** [comment]
> I upgrade pyarrow to `2.0.0`, then the problem disappears. Thank you very much.

Thank your report, we will add a hint in our error message.
