### ISSUE TITLE
[BUG][mars on ray] Failed to run in ray cluster mode.

### ISSUE THREAD

**Issue by fyrestone** [mars-project/mars#1711]
**Describe the bug**
Ray cluster will load code from local (not deserialize from bytes), but mars `RemoteMetaStore` is nested in `RayStorage` class. Ray worker can't load the `RemoteMetaStore` from local code.

```
2020-11-17 16:48:29,349	WARNING worker.py:1157 -- Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.6/site-packages/ray/function_manager.py", line 445, in _load_actor_class_from_local
    actor_class = getattr(module, class_name)
AttributeError: module 'mars.ray.core' has no attribute 'RemoteMetaStore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 563, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 567, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 364, in ray._raylet.execute_task
  File "/home/admin/.local/lib/python3.6/site-packages/ray/function_manager.py", line 394, in load_actor_class
    job_id, actor_creation_function_descriptor)
  File "/home/admin/.local/lib/python3.6/site-packages/ray/function_manager.py", line 454, in _load_actor_class_from_local
    class_name))
RuntimeError: Actor RemoteMetaStore failed to be imported from local code.
An unexpected internal error occurred while the worker was executing a task.
```

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Python 3.6.5
2. pymars 0.6.0b2
3. ray 1.0.1
4. Minimal reproduce example.
``` python
from mars.session import new_session

ray_session = new_session(backend='ray', _load_code_from_local=True).as_default()
print(ray_session)


def main():
    import mars.dataframe as md
    import mars.tensor as mt
    t = mt.random.rand(100, 4, chunk_size=30)
    df = md.DataFrame(t, columns=list('abcd'))
    print(df.describe().execute())


if __name__ == "__main__":
    main()
```

**Expected behavior**

**Additional context**

**Comment by qinxuye** [comment]
Any idea about how to address the problem?

**Comment by fyrestone** [comment]
> Any idea about how to address the problem?

Just move the `RemoteMetaStore` class outside the `RayStorage` class. Make the `RemoteMetaStore` visible at the module level.

**Comment by qinxuye** [comment]
> > Any idea about how to address the problem?
> 
> Just move the `RemoteMetaStore` class outside the `RayStorage` class. Make the `RemoteMetaStore` visible at the module level.

Great, so how about submitting a PR?

**Comment by fyrestone** [comment]
> > > Any idea about how to address the problem?
> > 
> > 
> > Just move the `RemoteMetaStore` class outside the `RayStorage` class. Make the `RemoteMetaStore` visible at the module level.
> 
> Great, so how about submitting a PR?

OK. I will create a fix PR.

**Comment by raulchen** [comment]
@fyrestone can you also fix this issue on the Ray side? I guess it's because we lost the parent class information in the function descriptor.

**Comment by fyrestone** [comment]
> @fyrestone can you also fix this issue on the Ray side? I guess it's because we lost the parent class information in the function descriptor.

OK. I will create a fix PR for ray, too. But, if a remote function / actor is defined in a function, we can't load it from local code. It's better to load code from both local code and serialized code in the future.
