### ISSUE TITLE
[BUG] missing a default timeout parameter and timeout error mismatch when deploying on yarn 

### ISSUE THREAD

**Issue by smartguo** [mars-project/mars#1791]
**Describe the bug**
missing a default timeout parameter and timeout error mismatch when deploying on yarn 

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.7.9
2. The version of Mars you use: pymars[distributed]==0.6.0
3. Versions of crucial packages, such as numpy, scipy and protobuf: numpy==1.19.4, scipy==1.5.4, protobuf==3.14.0, pyarrow==2.0.0
4. Full stack of the error.
```bash
Traceback (most recent call last):
  File "test_yarn.py", line 10, in <module>
    cluster = new_cluster(environment='python:///opt/anaconda3/envs/pymodel/bin/python', scheduler_num=1, web_num=1,worker_num=4, worker_cpu=8, worker_mem='28g',min_worker_num=2)
  File "/opt/anaconda3/envs/pymodel/lib/python3.7/site-packages/mars/deploy/yarn/client.py", line 148, in new_cluster
    timeout=timeout - (time.time() - check_start_time))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```
By adding a timeout parameter, the error disappear. But sometimes timeout error occurs as follows:
```bash
Traceback (most recent call last):
  File "test_yarn.py", line 10, in <module>
    cluster = new_cluster(environment='python:///opt/anaconda3/envs/pymodel/bin/python', scheduler_num=1, web_num=1,worker_num=4, worker_cpu=8, worker_mem='28g',min_worker_num=2, timeout=1)
  File "/opt/anaconda3/envs/pymodel/lib/python3.7/site-packages/mars/deploy/yarn/client.py", line 148, in new_cluster
    timeout=timeout - (time.time() - check_start_time))
  File "/opt/anaconda3/envs/pymodel/lib/python3.7/site-packages/mars/deploy/utils.py", line 31, in wait_services_ready
    raise TimeoutError('Wait kubernetes cluster start timeout')
TimeoutError: Wait kubernetes cluster start timeout
``` 
5. Minimized code to reproduce the error.
```python
import os
from mars.deploy.yarn import new_cluster
from mars.session import Session
import mars.tensor as mt
import mars.dataframe as md

os.environ['JAVA_HOME'] = '/usr/java/jdk1.8.0_191-amd64'
os.environ['HADOOP_HOME'] = "/usr/bin/hadoop"
cluster = new_cluster(environment='python:///opt/anaconda3/envs/pymodel/bin/python', scheduler_num=1, web_num=1,worker_num=4, worker_cpu=8, timeout=1)
print(Session.default_or_local().endpoint)
a = mt.random.rand(10, 10)
print(a.dot(a.T).execute())
```

**Expected behavior**
1. give timeout a default value, such as 60.
2. when timeout error occurs, print the correct info, E.g. "Wait yarn cluster start timeout"

**Comment by wjsi** [comment]
When timeout is not specified, it might be better to wait infinitely till KeyboardInterrupt is raised.

**Comment by smartguo** [comment]
@wjsi  waitting infinitely till KeyboardInterrupt is better. By the way, TimeoutError raised by the func `wait_services_ready`, how do you like adding a parameter naming `platform` to raise the corresponding cluster timout such as k8s or yarn.

**Comment by wjsi** [comment]
> @wjsi waitting infinitely till KeyboardInterrupt is better. By the way, TimeoutError raised by the func `wait_services_ready`, how do you like adding a parameter naming `platform` to raise the corresponding cluster timeout such as k8s or yarn.

It is cleaner to raise a general error inside ``wait_services_ready``. Different clients for different platforms can catch this error and raise their own using ``raise ... from None``.

**Comment by qinxuye** [comment]
Could you please submit a PR to address this issue please? @smartguo

**Comment by smartguo** [comment]
> Could you please submit a PR to address this issue? @smartguo

My pleasure, I will try my best.
