### ISSUE TITLE
Support specifying missing value for `tensor.tosparse()`

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#1795]
**Is your feature request related to a problem? Please describe.**

For now, `tensor.tosparse()` will just treat 0 as missing value, we can allow specifying another missing value.

**Describe the solution you'd like**

e.g. support `tensor.tosparse(missing=np.nan)`.

**Comment by smartguo** [comment]
can we set missing with multiple value? For example, `tensor.tosparse(missing=[np.nan, -9999])`

**Comment by qinxuye** [comment]
> can we set missing with multiple values? For example, `tensor.tosparse(missing=[np.nan, -9999])`

Do you mean the value that is nan **or** -9999 will be treated as missing value?

**Comment by smartguo** [comment]
> > can we set missing with multiple values? For example, `tensor.tosparse(missing=[np.nan, -9999])`
> 
> Do you mean the value that is nan **or** -9999 will be treated as missing value?

Yes. But we can replace other value such as -9999 into `np.nan` in advance, I'm not sure which operation is better.

**Comment by qinxuye** [comment]
> > > can we set missing with multiple values? For example, `tensor.tosparse(missing=[np.nan, -9999])`
> > 
> > 
> > Do you mean the value that is nan **or** -9999 will be treated as missing value?
> 
> Yes. But we can replace other value such as -9999 into `np.nan` in advance, I'm not sure which operation is better.

OK, I have already implemented it, `missing` can be multiple values, any of them will be treated as missing value.
