### ISSUE TITLE
[BUG] Tests failed with pandas-1.2.0

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#1845]
**Describe the bug**
Some cases failed with pandas 1.2.0 in CI

- [ ] FAILED mars/dataframe/arithmetic/tests/test_arithmetic_execution.py::TestBinary::testChained

- [ ] FAILED mars/dataframe/arithmetic/tests/test_arithmetic_execution.py::TestBinary::testRfunc

- [ ] FAILED mars/dataframe/arithmetic/tests/test_arithmetic_execution.py::TestBinary::testSameIndex

- [ ] FAILED mars/dataframe/arithmetic/tests/test_arithmetic_execution.py::TestBinary::testWithMultiForms

- [ ] FAILED mars/dataframe/arithmetic/tests/test_arithmetic_execution.py::TestBinary::testWithPlainValue

- [ ] FAILED mars/dataframe/base/tests/test_base.py::Test::testCut - AttributeError...

- [ ] FAILED mars/dataframe/base/tests/test_base.py::Test::testTransform - TypeErro...

- [ ] FAILED mars/dataframe/base/tests/test_base_execution.py::Test::testCutExecution

- [ ] FAILED mars/dataframe/base/tests/test_base_execution.py::Test::testTransformExecute

- [ ] FAILED mars/dataframe/base/tests/test_base_execution.py::Test::testTransformWithArrowDtypeExecution

- [ ] FAILED mars/dataframe/datasource/tests/test_datasource_execution.py::Test::testInitializerExecution

- [ ] FAILED mars/dataframe/datasource/tests/test_datasource_execution.py::Test::testReadCSVExecution

- [ ] FAILED mars/dataframe/datasource/tests/test_datasource_execution.py::Test::testReadCSVWithoutIndex
- [ ] FAILED mars/dataframe/indexing/tests/test_indexing_execution.py::Test::testOptimization
- [ ] FAILED mars/dataframe/reduction/tests/test_reduction.py::TestReduction::testDataFrameReduction
- [ ] FAILED mars/dataframe/reduction/tests/test_reduction_execute.py::TestReduction::testDataFrameLevelReduction
- [ ] FAILED mars/dataframe/reduction/tests/test_reduction_execute.py::TestReduction::testDataFrameReduction
- [ ] FAILED mars/dataframe/reduction/tests/test_reduction_execute.py::TestCount::testUseArrowDtypeNUnique
- [ ] FAILED mars/dataframe/tests/test_arrays.py::Test::testArrowStringArrayFunctions

**Comment by sighingnow** [comment]
FYI: vineyard tracks the issue at https://github.com/alibaba/libvineyard/issues/112.
