### ISSUE TITLE
[BUG][DISTRIBUTED] client may hang if something wrong happens in the scheduler

### ISSUE THREAD

**Issue by chineking** [mars-project/mars#19]
**Describe the bug**

If some errors occur in the distributed, the client may hang, #8 and #17 are examples.

**To Reproduce**

As examples in #8 and #17.

**Expected behavior**

Either we deliver the error to the client, or we hide the real error and deliver an InternalServerError to the client.

**Additional context**

We should separate the system error with the user caused error. We should add some tests.

**Comment by NJUPole** [comment]
`GraphActor.stop_graph` will raise `KeyError` when operand actor hasn't been created.

**Comment by chineking** [comment]
Add the code below to mars.deploy.local.tests.test_cluster.Test.testMultipleOuputTensorExecute, the stop graph will fail and the client still hang.

```python
with new_session(cluster.endpoint) as session2:
        U_result, s_result = session2.run(U + 1, s + 1)
        U_expected, s_expectd, _ = np.linalg.svd(raw, full_matrices=False)

        np.testing.assert_allclose(U_result, U_expected + 1)
        np.testing.assert_allclose(s_result, s_expectd + 1)
```
