### ISSUE TITLE
Failed to start local cluster in Linux

### ISSUE THREAD

**Issue by shizhiqiang007** [mars-project/mars#1941]
Source code:

```python
import mars.tensor as mt
from mars.deploy.local import new_cluster
from mars.session import new_session

cluster = new_cluster()

# new cluster will start a session and set it as default one
# execute will then run in the local cluster
a = mt.random.rand(10, 10)
a.dot(a.T).execute()

# cluster.session is the session created
(a + 1).execute(session=cluster.session)

# users can also create a session explicitly
# cluster.endpoint needs to be passed to new_session
session2 = new_session(cluster.endpoint)
(a * 2).execute(session=session2)
```

Error:

```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by wjsi** [comment]
Use

```python
if __name__ == '__main__':
    main()
```

and write all your code inside a ``main()`` function can resolve this issue.

**Comment by wjsi** [comment]
Please use English to describe your issue and organize your contents neatly.

**Comment by shizhiqiang007** [comment]
> Use
> 
> ```python
> if __name__ == '__main__':
>     main()
> ```
> 
> and write all your code inside a `main()` function can resolve this issue.



> Use
> 
> ```python
> if __name__ == '__main__':
>     main()
> ```
> 
> and write all your code inside a `main()` function can resolve this issue.

I used what you said, but it still doesn't work
souce code:
import mars.tensor as mt
from mars.deploy.local import new_cluster
from mars.session import new_session

def main():
    cluster = new_cluster()

    # new cluster will start a session and set it as default one
    # execute will then run in the local cluster
    a = mt.random.rand(10, 10)
    a.dot(a.T).execute()

    # cluster.session is the session created
    (a + 1).execute(session=cluster.session)

    # users can also create a session explicitly
    # cluster.endpoint needs to be passed to new_session
    session2 = new_session(cluster.endpoint)
    (a * 2).execute(session=session2)

if __name__ == "__main__":
    main()

error message:
AttributeError: 'NoneType' object has no attribute 'put'
2021-01-28T07:16:03Z <Greenlet at 0x7fa63ef8a648: <built-in method on_receive of mars.actors.pool.gevent_pool.Dispatcher object at 0x7fa63efd9408>(b'\x03\x01 \x00\x00\x00\x00\x00\x00\x009\xfcS\xc8\)> failed with AttributeError

**Comment by qinxuye** [comment]
@shizhiqiang007 

Actually, it succeeded, but when cluster shutdown, the error emerges because the main process exited, you can print the result and it will reveal the data in the main function.

We will suppress the message when cluster exits.
