### ISSUE TITLE
mars tensor can achieve something like numpy  np.insert()、np.delete() api?

### ISSUE THREAD

**Issue by shizhiqiang007** [mars-project/mars#2005]
Found no similar implementation like numpy   np.insert()、np.delete() api， Can this function be achieved？

**Comment by qinxuye** [comment]
Thank you for your proposal, we will implement it ASAP.

**Comment by shizhiqiang007** [comment]
> Thank you for your proposal, we will implement it ASAP.

Excuse me, when will this update version
