### ISSUE TITLE
dataframe operation stuck for distributed deployment?

### ISSUE THREAD

**Issue by leolle** [mars-project/mars#2074]
Hi, 10 million rows of data is read into a dataframe from clickhouse database, any calculating operation  like groupby sum operation will stuck there forever after I execute on distribute system, how should I fix this?

I have 3 servers, all of them are centos 7.6.2 system, python 3.7.3, pymars 0.6.6.
all of them have 80G+ free memory available.

1 scheduler:
mars-scheduler -a 192.168.4.35 -p 8200
1 web service
mars-web -a 192.168.4.31 -p 8100 -s 192.168.4.35:8200
1 worker:
mars-worker -a 192.168.4.33 -p 8200 -s 192.168.4.35:8200

```python
new_session('http://192.168.4.31:8100').as_default()
from sqlalchemy import create_engine
engine = create_engine('clickhouse://{user}:{password}@{host}:8130/{schema}'.format(**config['db']))
md_records = md.read_sql_table("mid_t_kc21", engine)
md_records.columns.execute()
```
scheduler and worker show such error:
AttributeError: 'DataFrameReadSQL' object has no attribute 'usecols'

**Comment by hekaisheng** [comment]
It's a bug in our optimizations, we will fix it ASAP.

You can turn off the optimization using the below command as a workaround now,
```
mars-scheduler -a 192.168.4.35 -p 8200 -Doptimize_tileable_graph=false
mars-worker -a 192.168.4.33 -p 8200 -s 192.168.4.35:8200 -Doptimize_tileable_graph=false
```

**Comment by hekaisheng** [comment]
Could you please provide the full error stack? I can't reproduce this issue in my environment.

**Comment by wjsi** [comment]
@hekaisheng This can be reproduced with ``md.read_sql_table('test', uri, chunk_size=4)[['a', 'b']]``.
