### ISSUE TITLE
[BUG] Mars import deadlock

### ISSUE THREAD

**Issue by chaokunyang** [mars-project/mars#2113]
**Describe the bug**
When running mars on ray after merged #2109, import mars on remote worker will raise `import dead lock error`. 
After commented lines 
```
from .core.session import new_session, execute, fetch, stop_server
# register
from .deploy.oscar.session import Session
del Session
```
Everything works fine.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version py3.1
2. The version of Mars you use: mars master 
3. Versions of crucial packages, such as numpy, scipy and pandas: latest
4. Full stack of the error.
![image](https://user-images.githubusercontent.com/12445254/116247799-cc0c6300-a79d-11eb-8443-385bd1d25711.png)
![image](https://user-images.githubusercontent.com/12445254/116247852-d75f8e80-a79d-11eb-8383-c8b977b9701a.png)

5. Minimized code to reproduce the error.
TODO

**Expected behavior**
Import deadlock shouldn't happen in any cases when `import mars` got executed

**Comment by qinxuye** [comment]
I can do `from mars import new_session` without deadlock error based on master branch, will close it first, reopen if problem exists still.
