### ISSUE TITLE
Implements `mars.learn.metrics.roc_auc_score`

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#2267]
**Is your feature request related to a problem? Please describe.**

`mars.learn.metrics.roc_auc_score` can be added.

**Comment by Divyanshu-Singh-Chauhan** [comment]
Yes, looks like two more functions needed to be added before adding roc_auc_score which are
1. _**_binary_roc_auc_score**_
2. _**_multiclass_roc_auc_score**_
I'll first try **__binary_roc_auc_score_** function.

**Comment by qinxuye** [comment]
> Yes, looks like two more functions needed to be added before adding roc_auc_score which are
> 
> 1. _**_binary_roc_auc_score**_
> 2. _**_multiclass_roc_auc_score**_
>    I'll first try **__binary_roc_auc_score_** function.

Sounds great, just send a PR if this part of job is free, feel free to ask question if you encounter any issue.

**Comment by Divyanshu-Singh-Chauhan** [comment]
Sure, @qinxuye 
Isn't there an analogous function to **_numpy.interp()_** in mars framework for linear 1D interpolation?
I believe adding that would be beneficial if not already present.

**Comment by qinxuye** [comment]
> Sure, @qinxuye
> Isn't there an analogous function to **_numpy.interp()_** in mars framework for linear 1D interpolation?
> I believe adding that would be beneficial if not already present.

Yeah, `np.interp()` is absent, could you open an issue about it?
