### ISSUE TITLE
How to perform all tensor on np.array packages

### ISSUE THREAD

**Issue by SunYanCN** [mars-project/mars#232]
Example：
```
import mars.tensor as mt
import numpy as np

def test_x():
    X1 = mt.tensor([0, 1])
    X2 = mt.tensor([2, 3])
    X = np.array([X1,X2])
    print(X.execute())
```
How to calculate X？

**Comment by chineking** [comment]
```python
X = np.array([X1, X2])
```
is not supported, so does

```python
X = mt.array([X1, X2])
```

Try to use `mt.stack` instead.

```python
In [32]: X = mt.stack([X1, X2])                                                     

In [33]: X.execute()                                                                
Out[33]: 
array([[0, 1],
       [2, 3]])
```

Maybe we can detect the argument for `mt.tensor` which `mt.array` calls internal, if it's a list/tuple and all object is a tensor-compatible object, call `mt.stack` to create a tensor.

I think if you are interested in this job, how about trying to solve it and opening a PR? Thanks in advance.

**Comment by SunYanCN** [comment]
Ok, I will try it!

**Comment by chineking** [comment]
Sorry to find that some relative code already exists, but not considered the `list` type, cc https://github.com/mars-project/mars/blob/master/mars/tensor/expressions/datasource/array.py#L126

Fix it is rather simpler, anyway, worth for firstly participating the development of Mars.

**Comment by chineking** [comment]
I found that this part of code is lack of unittest, since the fix itself is quite simple, come up with more tests please.

Unittests can be added to https://github.com/mars-project/mars/blob/00fc3a04616c233d9616030bb93323da1a56100e/mars/tensor/expressions/tests/test_core.py#L266
