### ISSUE TITLE
Tileable subtask structure visualization

### ISSUE THREAD

**Issue by RandomY-2** [mars-project/mars#2384]
**Is your feature request related to a problem? Please describe.**
When visualizing the tileable graph, we can also include a dag visualization for the subtask structure of each tileable, which can help us better control the progress of tileable. 

**Describe the solution you'd like**
We can create an API endpoint to return the subtask dag structure based on the tileable id. The json returned can be something similar to the json returned from the tileable graph endpoint. For example: 

```
{
     dependencies: [
          { from_subtask_id, to_subtask_id }, 
          ...
     ],

     subtasks: [
          { subtask_id, subtask_name, subtask_progress, subtask_status },
          ...
     ],
}
```

Then on the web, when user clicks on a tileable, the selected tileable's subtask graph can be displayed on the right side tileable detail panel, and the progress and color will be updated periodically just like the progress of the dag.

**Comment by wjsi** [comment]
As number of subtasks may be large, it is better to display them as small circles without text.

**Comment by wjsi** [comment]
Already done.
