### ISSUE TITLE
[PROPOSAL] New fusion strategy based on coloring algorithm

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#2435]
# New fusion strategy based on coloring algorithm

## Background

From perspective of execution, Mars schedules subtask graph to workers to achieve parallelism. Each subtask is consist of one or more chunks except for fetch chunk.

Graph below illustrates the process:

<img width="860" alt="image-20210906164438904" src="https://user-images.githubusercontent.com/357506/132339974-7e541857-ef76-45ad-bb13-c89ef73a4ec7.png">

Till this proposal written, current fusion strategy is relatively simple, that is, try to fuse the straight line that has at least 2 nodes. So as illustrated in the graph, only chunk 3 and 4 can be fused, and the final subtask graph will be consist of 5 subtasks.

## New coloring based algorithm

This proposal tries to propose a new coloring based algorithm. Steps include:

1. Coloring the initial nodes according to the bands that assigned by assigner.
2. Propagate color in the topological order, if the input nodes have same color, color it with the same color; otherwise, color with a new color.
3. Propagate with reversed topological order, check a node with its inputs, if all inputs have different color with itself, skip; otherwise, if some of inputs have the same color, but some others have different color, color the input nodes with same one  with a new color, and propagate to its inputs and so on.

Below will show some examples.

### Example 1

<img width="574" alt="image-20210907181827625" src="https://user-images.githubusercontent.com/357506/132340029-b595afcf-3cec-44cb-b1c3-aac379e2e607.png">

The ops of 1 and 2 colored with 1 and ops of 5 and 6 colored with 2, then color will propagate as topological order, op of 3 will notice only one kind of color received, then it will be colored with 1 too, so does op of 4. 

Propagate in a reverse topological order will not notice any inconsistency. Just skip.

Finally, the entire graph will only be colored with two colors, the nodes with same color can be fused, hence it will be separated into 2 subtasks.

### Example 2

<img width="761" alt="image-20210907192948585" src="https://user-images.githubusercontent.com/357506/132340055-f08106dd-b507-4e24-bc79-8364d6e1ef79.png">

The ops of 1 and 2 colored with 1, and ops of 9 and 10 colored with 2. Propagate with topological order; 3, 4, 5 with color 1; 11, 12 with color 2; 6, 7 with color 3; 8 with color 4; 13 with color 5.

Then check in a reversed topological order, 3 will find that 4 has same color 1 but 5 has different color 3, conflict happens, so node 4 will be colored with a new color 6, propagate to node 5 with same color. So for the node 12, it will be colored with 7.

 the entire chunk graph will be consist of 7 subtasks.

## Configuration

Some configuration could be added.

1. Max size of same color for start ops. For the ops that allocated to same band, we should limit the size of same color, fuse too much may decrease the concurrency.
2. Max successors that can be propagated with same color. For those op comes up with plenty of successors, we should limit the size that can be propagated.

**Comment by chaokunyang** [comment]
Is there any heuristic for limiting max size of same color for start ops? At the start of autoscaling, there will be only one band and if we don't limt  max size of same color for start ops, the whole chunk graph mayb be fused to one subtask.

**Comment by qinxuye** [comment]
> Is there any heuristic for limiting max size of same color for start ops? At the start of autoscaling, there will be only one band and if we don't limt max size of same color for start ops, the whole chunk graph mayb be fused to one subtask.
> And the quantity of workers will affect the fused chunk graph, how will the new fuse algorithm work when autoscaling is enabled?

#1 of configuration section is talking about this. There will be a limit and I'd prefer to set a relatively small size, maybe 2 at most.
