### ISSUE TITLE
Provide a common api for mars cluster

### ISSUE THREAD

**Issue by NJUPole** [mars-project/mars#25]
**Is your feature request related to a problem? Please describe.**
Now, when create a mars cluster, we must start mars web and interact via RESTful API, however it's not necessary in some cases if we don't need web UI.

**Describe the solution you'd like**
I think a common api should be provided and interact with scheduler via it. Like
```
from mars import MarsApi

api = MarsApi(scheduler_ip)
api.create_session(session_id)
api.submit_graph(session_id, graph)
```

**Additional context**
It may be useful when create a local cluster.

**Comment by chineking** [comment]
Since LocalCluster which described in #16 ，LocalCluster should own a MarsAPI.

I suggest that modify the import way slightly.

```python
from mars.api import MarsAPI
```
