### ISSUE TITLE
[BUG] map_chunk data incorrectness

### ISSUE THREAD

**Issue by chaokunyang** [mars-project/mars#2626]
**Describe the bug**
When call `df.map_chunk` in a loop and execute it by `mars.execute`, the returned dataframe are the same by mistake.

**To Reproduce**
1. Python version: py3.7
2. The version of Mars: master
3. Minimized code to reproduce the error:
```python
df = md.DataFrame(mt.random.rand(4, 2, chunk_size=2)).execute()
df.to_pandas()

import mars
dtypes=pd.Series([np.dtype(float) for i in range(df.shape[1])])
executables = []
for i in range(1, 3):
    print(f"i {i}", df.map_chunk(lambda x: x[i-1:i], output_type='dataframe', dtypes=dtypes).to_pandas())
    executables.append(df.map_chunk(lambda x: x[i-1:i], output_type='dataframe', dtypes=dtypes))
mars.execute(executables)
mars.fetch(executables)
```

**Expected behavior**
Two executable should return different data instead of return same data.
![image](https://user-images.githubusercontent.com/12445254/147442370-7b4b40aa-9164-4e29-b142-49189689884b.png)

**Comment by wjsi** [comment]
`df` and lambda function itself is not changed inside the loop, hence result will not change. Try use `args` argument to set input arguments for lambdas. The behavior is consistent with Python closures, and we have no intention to fix it.

**Comment by chaokunyang** [comment]
Thanks, using `args` argument works.
