### ISSUE TITLE
[BUG] Groupby().agg() returned a DataFrame with index even as_index=False

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#2645]
**Describe the bug**

Groupby().agg() returned a DataFrame with index even as_index=False.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version
2. The version of Mars you use
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
5. Minimized code to reproduce the error.

```
In [10]: def g(x):
    ...:     return (x == '1').sum()
    ...: 

In [11]: df = md.DataFrame({'a': ['1', '2', '3'], 'b': ['a1', 'a2', 'a1']})

In [12]: df.groupby('b', as_index=False)['a'].agg((g,)).execute()
/Users/qinxuye/Workspace/mars/mars/deploy/oscar/session.py:1932: UserWarning: 
Out[12]: 
    g
b    
a1  1
a2  0
```

**Comment by wjsi** [comment]
pandas shows the same behavior. Maybe we need to ask pahdas if it is a bug.

```python
In [5]: import pandas as pd
In [6]: pdf = pd.DataFrame({'a': ['1', '2', '3'], 'b': ['a1', 'a2', 'a1']})
In [7]: pdf.groupby('b', as_index=False)['a'].agg((lambda x: (x == "1").sum(),))
Out[8]: 
    <lambda>
b           
a1         1
a2         0
```
