### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [mars-project/mars#2660]
Problem
---------
On aarch64, `pip install pymars` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install pymars` should download the wheels from PyPI.

@qinxuye, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by wjsi** [comment]
Among all issues, adding supports for other archs is not of high priority. If we were adding this support, we may try using `cibuildwheel` to replace current implementation and support other archs like `universal2` and so on to simplify our continuous deployment process. I don't know if you are interested in this.

**Comment by wjsi** [comment]
Fixed in #2672.
