### ISSUE TITLE
Add XGBoost support for Mars learn

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#270]
**Is your feature request related to a problem? Please describe.**

I think maybe it's time for mars to extend the ecosystem to learning system. XGBoost would be a good first shot, we can treat it as the first support for `mars.learn`.

**Comment by chineking** [comment]
I have noticed that Dask team had a [fruitful discussion](https://github.com/dmlc/xgboost/issues/2032) with XGBoost team, and there is already a project named [dask-xgboost](https://github.com/dask/dask-xgboost). They are so fantastic that our job could be more easier.

**Comment by chineking** [comment]
Some updates are listed below.

1. XGBoost requires for a [dmlc tracker](https://github.com/dmlc/dmlc-core/blob/master/tracker/dmlc_tracker/tracker.py) started first with `nworker` specified to tell the dmlc distributed layer how many workers can be used. We can do this in an execution of a virtual node, the virtual node should rely on all the input chunks to make sure all data are processed.
2. XGBoost computation will start once all workers are ready, this is a potential issue that, Mars does not support all-or-nothing scheduling yet, which means if a worker of xgboost is triggered by Mars, the calculation slot is occupied, but the worker will do nothing until all the workers are ready. This could be sort of waste on worker resources.
