### ISSUE TITLE
[BUG] Warnings raised by pandas

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#2735]
**Describe the bug**
Warnings raised by pandas when call `groupby.agg`:

```
/home/admin/kaisheng.hks/mars/mars/dataframe/groupby/aggregation.py:741: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  grouped = grouped[selection]
```

**Comment by qinxuye** [comment]
This behavior is consistent with pandas, df.groupby()['a', 'b'] will have warnings, instead, df.groupby()[['a', 'b']] should be used, thus close this issue.
