### ISSUE TITLE
[BUG] `read_parquet.py` lint error

### ISSUE THREAD

**Issue by zhongchun** [mars-project/mars#2757]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5388750/155694431-3cba72cc-14de-433c-92b0-1141175810f5.png)

**To Reproduce**
master branch

**Comment by qinxuye** [comment]
Already addressed in #2755 .

**Comment by qinxuye** [comment]
Please rebase the master, this issue is gonna vanish.

**Comment by zhongchun** [comment]
This lint problem is caused by #2755. Maybe we should add `noqa: F821` to ignore it.

**Comment by zhongchun** [comment]
Thanks.
