### ISSUE TITLE
[BUG] There is a problem in the method `upload_slot_usages` of `workerslot.py` 

### ISSUE THREAD

**Issue by zhongchun** [mars-project/mars#2795]
In the method `upload_slot_usages` of `mars/services/scheduling/worker/workerslot.py`, 
![image](https://user-images.githubusercontent.com/5388750/157171674-a0e6dc7f-ce9d-413f-8f76-db35079655f7.png)
line 268 there is an error,  it should be 
```
delays.append(
    global_slots_ref.update_subtask_slots.delay(
        self._band, session_id, subtask_id, max(1.0, usage)
    )
)
```

**Comment by wjsi** [comment]
This is intended to be kept unfixed as there might cause task to be blocked. This line will be deprecated when better resource model is applied.
