### ISSUE TITLE
How to disable  console logs ?

### ISSUE THREAD

**Issue by tianlinzx** [mars-project/mars#2813]
There are a lot of logs in console , how to disable console logs output?
Note that the issue tracker is NOT the place for general support.  For
discussions about development, questions about usage, or any general questions,
we use our mailing list mars-dev@googlegroups.com.

**Comment by qinxuye** [comment]
You can redirect the stdout to files, not related to Mars itself. Will close this issue, feel free to open a new issue if you encounter any problem.
