### ISSUE TITLE
[Mars on ray] specify owner bottleneck

### ISSUE THREAD

**Issue by chaokunyang** [mars-project/mars#2877]
**Is your feature request related to a problem? Please describe.**
Currently calling `ray.put` in mars will specify supervisor as owner for:
- Avoid data lost when auto scale in workers
- Avoid data lost  when subpool actor died
But when there are shuffles, there will be m*n objects which need to specify supervisor as owner, and it makes too much AssignOwner rpc to supervisor, which makes supervisor as the bottleneck for the whole system. 

**Describe the solution you'd like**
- We can specify worker main pool as owner if autoscale is not enabled.
- If ray support auto ownership transfer, there will be no need to specify owner.

**Describe alternatives you've considered**

**Comment by wjsi** [comment]
@chaokunyang does #2878 fixes this issue?
