### ISSUE TITLE
[BUG] mars storage put too much shuffle meta to data manager and supervisor

### ISSUE THREAD

**Issue by chaokunyang** [mars-project/mars#2899]
**Describe the bug**

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.7.9
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
too much meta to data manager in main pool:
[put_data_info.log](https://github.com/mars-project/mars/files/8401983/put_data_info.log)
too much meta to supervisor:
[set_meta.log](https://github.com/mars-project/mars/files/8401982/set_meta.log)

5. Minimized code to reproduce the error.

**Expected behavior**
Mars should store as much less info for chunks in supervisor to avoid the supervisor single-point bottle-neck.
The mapper subtaks is about `1000~2000` subtasks, but the meta for every subtasks is about 1~3M, there is too much serialization and storage cost for those subtasks would be very large and the supervisor will be the bottleneck for the system. 

**Additional context**

**Comment by chaokunyang** [comment]
When mars running on ray, mars will store all ray object refs into worker main pool and supervisor, ray will deserialzie all thoes objectrefs and issue an rpc to the subpool, the io cost will be high, and the whole system will be hang

**Comment by qinxuye** [comment]
> issue an rpc to the subpool for every object ref

What's this RPC for?

**Comment by chaokunyang** [comment]
> > issue an rpc to the subpool for every object ref
> 
> What's this RPC for?

It's used by ray ownership protocal

**Comment by chaokunyang** [comment]
And for large-scale shuffle, the meta will be large. When  remove chunks, the remove chunks request message will be huge, serializing/deserializing such single message will take unbelieveable 15 seconds, and there will be thousands of such requests if there are thousands of mapper subtasks.

**Comment by chaokunyang** [comment]
![image](https://user-images.githubusercontent.com/12445254/162170628-aa21eb03-0b4c-4d9b-a961-609575daac86.png)
![image](https://user-images.githubusercontent.com/12445254/162170685-6042710c-fc01-4920-9d6b-3f1082d5b38d.png)
