### ISSUE TITLE
Add `is_broadcaster` property in `ChunkData`

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#2941]
A chunk that is depended by many chunks, we call it broadcaster, if its size is larger other dependencies, all downstream nodes may be scheduled to one worker. Here we add `is_broadcaster` hint to tell assigner do some special treatments.

**Comment by zhongchun** [comment]
Maybe we could add `is_broadcaster` to one_chunk and broadcast methods.

**Comment by hekaisheng** [comment]
> Maybe we could add `is_broadcaster` to one_chunk and broadcast methods.

Yes, I have implemented it in #2943 for both one_chunk and broadcast methods.
