### ISSUE TITLE
[BUG] Mars import took too long

### ISSUE THREAD

**Issue by chaokunyang** [mars-project/mars#3020]
**Describe the bug**
When `import mars`  first time, it took about 4~5 seconds which is pretty time-consuming for users
![image](https://user-images.githubusercontent.com/12445254/167792440-86729121-8d45-4320-bcbd-6e73eab936e8.png)
**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.7.9
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Expected behavior**
`import mars` should take less than 1 second, just like pandas:
![image](https://user-images.githubusercontent.com/12445254/167799642-eb6456c4-fc12-4e5b-9b5a-c4caf787e9c2.png)

**Additional context**

**Comment by wjsi** [comment]
Please run

```bash
python -X importtime -c "import mars"
```

and upload its outputs as a log file here.

**Comment by chaokunyang** [comment]
> Please run
> 
> ```shell
> python -X importtime -c "import mars"
> ```
> 
> and upload its outputs as a log file here.

[import.log](https://github.com/mars-project/mars/files/8668432/import.log)
