### ISSUE TITLE
What's about python version compatible?

### ISSUE THREAD

**Issue by cmsxbc** [mars-project/mars#3173]
It's able to install pymars on python3.7, but there is incompatible code, such as 
https://github.com/mars-project/mars/blob/60e19c359f0f3a8b6717e8d683922fd4efba22fd/mars/deploy/oscar/ray.py#L429

I'm not sure if there is more incompatible case...

**Comment by qinxuye** [comment]
Which code do you run to trigger the incompatibility? Can you paste it so that we can reproduce it.

**Comment by cmsxbc** [comment]
```
import ray
ray.init()
import mars
mars.new_ray_session(worker_num=2)
import mars.tensor as mt
mt.random.RandomState(0).rand(1000_0000, 5).sum().execute()
```

**Comment by qinxuye** [comment]
@chaokunyang @fyrestone @zhongchun Could you please check what's going on here? seems python 3.7 is not compatible with the ray backend.

**Comment by chaokunyang** [comment]
> @chaokunyang @fyrestone @zhongchun Could you please check what's going on here? seems python 3.7 is not compatible with the ray backend.

Seems the `force` argument in logging config is not compatible with py3.7, I will submit a fix later

**Comment by qinxuye** [comment]
@cmsxbc We will fix it soon, before we only test the compatibility for py3.8 about ray backend, and we will add the tests for 3.7 and other versions.
