### ISSUE TITLE
 Warnning from ray backend:The remote function 'ray.util.client.ommon.get_class_info' has been exported 100 times.

### ISSUE THREAD

**Issue by cmsxbc** [mars-project/mars#3181]
* Python: 3.7.11
* mars: 0.9.0
* ray: 1.9.2

```
import ray
import mars
import mars.tensor as mt

n = 20000

ray.init("ray://<my_ray_cluster_addr>")
mars.new_ray_session(worker_num=4, worker_cpu=4)
X = mt.random.RandomState(0).rand(n,n)
invX = mt.linalg.inv(X).execute()
``` 

And there is a warning
> "The remote function 'ray.util.client.common.get_class_info' has been exported 100 times. It's "
> "possible that this warning is accidental, but this "
> "may indicate that the same remote function is being "
> "defined repeatedly from within many tasks and "
> "exported to all of the workers. This can be a "
> "performance issue and can be resolved by defining "
> "the remote function on the driver instead. See "
> "https://github.com/ray-project/ray/issues/6240 for "
> "more discussion."

**Comment by fyrestone** [comment]
Could you try this?

``` python
import ray
import mars
import mars.tensor as mt

n = 20000

ray.init("ray://<my_ray_cluster_addr>")
# mars.new_ray_session(worker_num=4, worker_cpu=4)
mars.new_session(backend="ray")
X = mt.random.RandomState(0).rand(n,n)
invX = mt.linalg.inv(X).execute()
```

**Comment by cmsxbc** [comment]
@fyrestone It seems work, but what's difference? And maybe the document should be updated?

**Comment by fyrestone** [comment]
> @fyrestone It seems work, but what's difference? And maybe the document should be updated?

We introduced a new execution mode for Ray. Currently, the `mars.new_session(backend="ray")` can switch to the new Ray backend. We are adapting the `new_ray_session` to the new Ray backend. The document and API will be updated as soon as possible, Thanks.

**Comment by cmsxbc** [comment]
Ok,thanks~
