### ISSUE TITLE
[BUG] Ray task backend no progress

### ISSUE THREAD

**Issue by chaokunyang** [mars-project/mars#3216]
**Describe the bug**
Ray task mode doesn't update progress until whole task finished:
![image](https://user-images.githubusercontent.com/12445254/183634801-331c03f6-5a5d-4ba5-b11f-9645c0840e93.png)
**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.7.9
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
5. Minimized code to reproduce the error.
```python
def test_groupby(n=10):
    from datetime import datetime
    start = datetime.now()
    df = md.DataFrame(
    mt.random.rand(n * 500, 4, chunk_size=500),
    columns=list('abcd'))
    # print(df.sum().execute())
    result = df.groupby(['a']).apply(lambda pdf: pdf).execute()
    duration = datetime.now() - start
    return result, duration
mars.new_session(n_worker=10, n_cpu=10*2, backend="ray")
test_groupby(200)
```
**Expected behavior**

**Additional context**

**Comment by zhongchun** [comment]
I'll fix it soon.

**Comment by zhongchun** [comment]
There is a status bar and an a continuously updated value
![image](https://user-images.githubusercontent.com/5388750/184059557-9c17200b-ae50-496b-a9d4-040446b0e7d0.png)
