### ISSUE TITLE
[BUG]miniconda3/lib/python3.9/uuid.py", line 186, in __init__     raise ValueError('bytes is not a 16-char string')

### ISSUE THREAD

**Issue by gfkdliucheng** [mars-project/mars#3231]
**Describe the bug**

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version
2. The version of Mars you use
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Expected behavior**

**Additional context**

**Comment by gfkdliucheng** [comment]
CPU 无问题，GPU Ubuntu22.04 存在以下报错 ctypes ValueError: [address=127.0.0.1:33995, pid=381804] bytes is not a 16-char string

**Comment by qinxuye** [comment]
Do you have the code to help us to reproduce the error?

**Comment by gfkdliucheng** [comment]
import mars
mars.new_session()
import mars.tensor as mt

a = mt.random.uniform(-1, 1, size=(1000, 1000), gpu=True)

**Comment by qinxuye** [comment]
Thanks, will try to fix it ASAP.

**Comment by gfkdliucheng** [comment]
env：tesla v100  cuda11.3   Ubuntu 22.04
