### ISSUE TITLE
Question about Mars on Colab

### ISSUE THREAD

**Issue by KyonQi** [mars-project/mars#3236]
**Describe the bug**
I try to install Mars on Colab, but I meet the error on `mars.new_session()`

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: Python 3.7
2. The version of Mars you use: Mars 0.9.0
3. Versions of crucial packages, such as numpy, scipy and pandas: N/A
4. Full stack of the error：
```
ERROR:mars.services.cluster.uploader:Failed to upload node info
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mars/services/cluster/uploader.py", line 129, in upload_node_info
    band_quota_infos=self._band_quota_infos,
  File "/usr/local/lib/python3.7/dist-packages/mars/lib/aio/_threads.py", line 36, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mars/services/cluster/gather.py", line 185, in gather_node_details
    disk_io_usage = mars_resource.disk_io_usage()
  File "/usr/local/lib/python3.7/dist-packages/mars/resource.py", line 293, in disk_io_usage
    disk_counters = psutil.disk_io_counters()
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 2026, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/psutil/_pslinux.py", line 1115, in disk_io_counters
    for entry in gen:
  File "/usr/local/lib/python3.7/dist-packages/psutil/_pslinux.py", line 1088, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   7       0 loop0 47162 0 2075354 40330 17233 0 394760 7124 0 24336 31204 0 0 0 0\n'
ERROR:mars.services.cluster.uploader:Failed to upload node info: not sure how to interpret line '   7       0 loop0 47162 0 2075354 40330 17233 0 394760 7124 0 24336 31204 0 0 0 0\n'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-d29568a019a0> in <module>
      1 import mars
----> 2 mars.new_session()

25 frames
/usr/local/lib/python3.7/dist-packages/psutil/_pslinux.py in read_procfs()
   1086                 rtime = wtime = reads_merged = writes_merged = busy_time = 0
   1087             else:
-> 1088                 raise ValueError("not sure how to interpret line %r" % line)
   1089             yield (name, reads, writes, rbytes, wbytes, rtime, wtime,
   1090                    reads_merged, writes_merged, busy_time)

ValueError: [address=127.0.0.1:37551, pid=415] not sure how to interpret line '   7       0 loop0 47162 0 2075354 40330 17233 0 394760 7124 0 24336 31204 0 0 0 0\n'
```
5. Minimized code to reproduce the error.
```
import mars
mars.new_session()
```
**Expected behavior**
I can use Mars in Colab successfully.

**Additional context**
N/A

**Comment by fyrestone** [comment]
Looks like a psutil bug, which version is your psutil? `pip show psutil` prints the version info.

**Comment by KyonQi** [comment]
> Looks like a psutil bug, which version is your psutil? `pip show psutil` prints the version info.

It's psutil 5.4.8
```
Name: psutil
Version: 5.4.8
Summary: Cross-platform lib for process and system monitoring in Python.
Home-page: https://github.com/giampaolo/psutil
Author: Giampaolo Rodola
Author-email: [g.rodola@gmail.com](mailto:g.rodola@gmail.com)
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: distributed
```

**Comment by chaokunyang** [comment]
> > Looks like a psutil bug, which version is your psutil? `pip show psutil` prints the version info.
> 
> It's psutil 5.4.8
> 
> ```
> Name: psutil
> Version: 5.4.8
> Summary: Cross-platform lib for process and system monitoring in Python.
> Home-page: https://github.com/giampaolo/psutil
> Author: Giampaolo Rodola
> Author-email: [g.rodola@gmail.com](mailto:g.rodola@gmail.com)
> License: BSD
> Location: /usr/local/lib/python3.7/dist-packages
> Requires: 
> Required-by: distributed
> ```

Could you upgrade `psutil` to latest version and try `mars` again?

**Comment by KyonQi** [comment]
> > > Looks like a psutil bug, which version is your psutil? `pip show psutil` prints the version info.
> > 
> > 
> > It's psutil 5.4.8
> > ```
> > Name: psutil
> > Version: 5.4.8
> > Summary: Cross-platform lib for process and system monitoring in Python.
> > Home-page: https://github.com/giampaolo/psutil
> > Author: Giampaolo Rodola
> > Author-email: [g.rodola@gmail.com](mailto:g.rodola@gmail.com)
> > License: BSD
> > Location: /usr/local/lib/python3.7/dist-packages
> > Requires: 
> > Required-by: distributed
> > ```
> 
> Could you upgrade `psutil` to latest version and try `mars` again?

Thanks! I upgrade it and don't meet the error now.

**Comment by qinxuye** [comment]
Shall us to ensure that psutil >= some version? @fyrestone @chaokunyang

**Comment by fyrestone** [comment]
> Shall us to ensure that psutil >= some version? @fyrestone @chaokunyang

Good suggestion. Currently, Mars pins `psutil>=4.0.0` which is too old for some systems. Maybe `psutil>=5.9.0` is good for Mars.

**Comment by fyrestone** [comment]
This is the change logs of psutil, 5.9.0 has released at 2021-12-29, and it fixes many bugs. https://github.com/giampaolo/psutil/blob/master/HISTORY.rst
