### ISSUE TITLE
[BUG] Exception when matmul matrix in distributed version

### ISSUE THREAD

**Issue by zouwan** [mars-project/mars#360]
**Describe the bug**
I get exception when matrix dim is 4096 everytime on mars cluster (bug matrix dim 1024 is ok) 

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version : python 2.7

2. The version of Mars you use:  pymars[distributed]

3. Versions of crucial packages, such as numpy, scipy and protobuf

4. Full stack of the error.
  ```
File "benchmark-mars-cluster.py", line 21, in <module>
    sess.run(np.matmul(m1, m2, out=m3))
  File "/home/odin/zouwan/.local/lib/python2.7/site-packages/mars/session.py", line 117, in run
    execute_result = self._sess.run(*idx_to_run_tensors.values(), **kw)
  File "/home/odin/zouwan/.local/lib/python2.7/site-packages/mars/web/session.py", line 125, in run
    resp_json = self._submit_graph(graph_json, targets_join)
  File "/home/odin/zouwan/.local/lib/python2.7/site-packages/mars/web/session.py", line 202, in _submit_graph
    target=targets,
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

5. Minimized code to reproduce the error.
```#! /usr/bin/python

import sys
import numpy as raw_np
import mars.tensor as np
import time

from mars.session import new_session
sess = new_session('http://10.89.194.12:8009')

m1_file = sys.argv[1]   // matrix file
m2_file = sys.argv[2]

m1 = np.tensor(raw_np.loadtxt(m1_file), chunk_size=1000)
m2 = np.tensor(raw_np.loadtxt(m2_file), chunk_size=1000)
m3 = np.zeros(m1.shape)

start = time.time()
sess.run(np.matmul(m1, m2, out=m3))
end = time.time()

print m3

print 'Time:', (end - start) * 1000.0
```

**Expected behavior**
```
time python benchmark-mars-cluster.py 1 1024A.matrix 1024B.matrix
<mars.tensor.core.Tensor object at 0x52bf980>
Time: 9026.78394318

real    0m13.782s
user    0m7.068s
sys     0m4.415s
```

**Additional context**

**Comment by chineking** [comment]
Please add the commands that you started the distributed runtime, especially the one to start web ui.

**Comment by zouwan** [comment]
1. mars-web
nohup mars-web -a 10.90.21.62 -s 10.90.21.62:8301 -p 8302 --ui-port 8009 > log/mars-web.log &

2. mars-scheduler
nohup mars-scheduler  -a 10.90.21.62 -p 9001  > log/scheduler.log  &

3. mars-worker
nohup mars-worker -a 10.90.21.62  -p 8302 -s 10.90.21.62:8301 --cache-mem 512m --phy-mem 90% 2>&1 > log/mars-work.log &
nohup mars-worker -a 10.89.194.12 -p 8302 -s 10.90.21.62:8301 --cache-mem 512m --phy-mem 90% > log/mars-work.log &
nohup mars-worker -a 10.89.177.63 -p 8302 -s 10.90.21.62:8301 --cache-mem 512m --phy-mem 90% > log/mars-work.log &

**Comment by chineking** [comment]
> sess = new_session('http://10.89.194.12:8009')

This seems a worker's address, instead of the web address?

**Comment by zouwan** [comment]
8009 is web ui port

**Comment by chineking** [comment]
> mars-web
> nohup mars-web -a 10.90.21.62 -s 10.90.21.62:8301 -p 8302 --ui-port 8009 > log/mars-web.log &

I mean there the web address is 10.90.21.62, but you `new_session` with 10.89.194.12

**Comment by chineking** [comment]
I notice that you can calculate the data with less dimension, but fail on larger one. This could be caused by the data which is too large for web ui to handle, you can try `session.run(x, fetch=False)` to prevent from fetching data.

Besides, check the log file of web to see if there is any useful information.

**Comment by zouwan** [comment]
now it run good!

thanks
