### ISSUE TITLE
Add docs to explain the internals

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#460]
**Is your feature request related to a problem? Please describe.**

We should add some docs to explain the internals of Mars.

**Comment by wjsi** [comment]
Contents

1. Structure
   1. Code structure
   2. How tasks are executed
2. Oscar actor system
   1. Actor creation
   2. Actor execution
   3. Communication and routing
   4. Batch methods
3. Service topics
   1. Cluster
   2. Lifecycle
   3. Meta
   4. Scheduling
   5. Session
   6. Storage
   7. Subtask
   8. Task
   9. Web
