### ISSUE TITLE
Fix the str representation for TensorChunkData and ChunkData

### ISSUE THREAD

**Issue by sighingnow** [mars-project/mars#468]
Is there any particular reason to hide the `Data` suffix in `__repr__` and `__str__` of `ChunkData` and `TensorChunkData`? It is quite misleading when debugging and I spent almost one hour to find out what happended and then realize it is not `Chunk`, but `ChunkData`.....

 Related code:

https://github.com/mars-project/mars/blob/3f0bd7a36a532a007533edf0809ad61f29e60969/mars/core.py#L228-L230

https://github.com/mars-project/mars/blob/3f0bd7a36a532a007533edf0809ad61f29e60969/mars/tensor/core.py#L92-L107

**Comment by chineking** [comment]
Yeah, I think we can repr Chunk data as `ChunkData <op=xxx, key=xxx>`, so does `TensorData`.

**Comment by sighingnow** [comment]
The `__repr__` and `__str__` are usually called when *the users* print a `Tensor` in python/ipython shell. To fix the issue and without affecting users, we have

+ plan A: move the `__repr__` and `__str__` from `TensorData` to `Tensor`, and display it as `Tensor`
+ plan A: implement `__repr__` and `__str__` in `TensorData` as `TensorData`, and add a corresponding `__repr__` and `__str__` in `Tensor` as well, displaying as `Tensor`. That would lead to a lot of code duplication.
+ plan C: just leave it as current implementation the ordinary users won't be affected

Personally speaking, I now prefer plan C (and close this issue as invalid 😢)

**Comment by NJUPole** [comment]
I also choose plan C, users don't need to know the difference between `Tensor` and `TensorData`.

So i will close this issue and anyone has other suggestions could reopen it.
