### ISSUE TITLE
Pending after local.new_cluster()

### ISSUE THREAD

**Issue by xiaonans** [mars-project/mars#487]
Program is pending in the while loop after 
`from mars.deploy.local import new_cluster`
`cluster = new_cluster()`

Installed from source.

I found the problem is caused by
`actor.post_create()` in LocalActorPool
when calling 
`self._node_info_ref = pool.create_actor(NodeInfoActor, uid=NodeInfoActor.default_uid())` in SchedulerService

Maybe I should go deeper to the c code,  but the core.c is a little bit hard to read.
Any suggestion on this program pending problem?

**Comment by qinxuye** [comment]
Could you please show us the simplified test file so that we can reproduce your problem? I don't have any clue according to your description.

**Comment by xiaonans** [comment]
The test file is very simple, just 
`from mars.deploy.local import new_cluster`
`cluster = new_cluster()`
Then the program is pending.

**Comment by qinxuye** [comment]
> The test file is very simple, just
> `from mars.deploy.local import new_cluster`
> `cluster = new_cluster()`
> Then the program is pending.

Local cluster is tested for ci, we never encounter this issue before. I doubt it may be related to the CUDA environment, check https://github.com/mars-project/mars/pull/480 to see if it's helpful, after the PR merged into master, you can give a try then to see if the issue exists still.

**Comment by qinxuye** [comment]
#480 has been merged, could you please try to install from master again, and check if the issue solved?

**Comment by xiaonans** [comment]
Issue solved after git pull and reinstall. Thanks! :)

**Comment by qinxuye** [comment]
Thanks, I will close this issue. Feel free to reopen if issue exists still.
