### ISSUE TITLE
Support fetching corner data

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#490]
**Is your feature request related to a problem? Please describe.**

Currently, `execute` and `fetch` will trigger fetching whole data to client. There are two main potential issues.

1. The data will be fetched to scheduler at first, assembled on it, then sent back to client, if the data is huge, scheduler will be doomed.
2. Mostly user just want to display the data, numpy etc will only show the edge data, fetching all data is definitely a waste.

Thus, I suggest to support fetching corner data, and set `corner=True` as default both for `execute` or `fetch`.

**Describe the solution you'd like**

According to [numpy doc](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.get_printoptions.html), we can get the `threshold` and `edgeitems` to decide how many corner data could be fetched.

**Comment by sighingnow** [comment]
FYI: [the `_build_repr_df` of modin](https://github.com/modin-project/modin/blob/master/modin/pandas/base.py#L44) looks interesting.
