### ISSUE TITLE
[BUG] Executor super slow when executing graph in which each tensor does not have more than 1 chunk

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#509]
**Describe the bug**

Executor super slow when executing graph in which each tensor does not more than 1 chunk.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.7.3
2. The version of Mars you use: master branch
3. Versions of crucial packages, such as numpy, scipy and protobuf
4. Full stack of the error.
5. Minimized code to reproduce the error.

`n_parallel=8`:

```
In [7]: import mars.tensor as mt                                                

In [8]: from mars.learn.datasets.samples_generator import make_low_rank_matrix  

In [9]: X = make_low_rank_matrix(n_samples=50, n_features=25, effective_rank=5, 
   ...:                          tail_strength=0.01, random_state=0)            

In [10]: s = mt.linalg.svd(X)[1]                                                

In [11]: %time (s.sum() - 5).execute(n_parallel=8)                              
CPU times: user 9.79 s, sys: 307 ms, total: 10.1 s
Wall time: 10.1 s
Out[11]: 0.08053185559911746
```

`n_parallel=1`:

```
In [1]: import mars.tensor as mt                                                

In [2]: from mars.learn.datasets.samples_generator import make_low_rank_matrix  

In [3]: X = make_low_rank_matrix(n_samples=50, n_features=25, effective_rank=5, 
   ...:                          tail_strength=0.01, random_state=0)            

In [4]: s = mt.linalg.svd(X)[1]                                                 

In [5]: %time (s.sum() - 5).execute(n_parallel=1)                               
CPU times: user 234 ms, sys: 82.9 ms, total: 317 ms
Wall time: 316 ms
Out[5]: 0.08053185559911746
```

**Comment by wjsi** [comment]
The code below will cost minutes, which causes worker failure as it blocks all the coroutines.

```python
import numpy as np
import random
from mars.tensor.expressions.fetch import TensorFetch
from mars.tensor.expressions.arithmetic import TensorTreeAdd
from mars.executor import Executor
from mars.graph import DAG

fetches = [TensorFetch(np.float64(), to_fetch_key=str(idx)).new_chunk([], shape=()) for idx in range(17000)]
adder_op = TensorTreeAdd(np.float64())
adder_chunk = adder_op.new_chunk(fetches, shape=())
dag = DAG()
[dag.add_node(c) for c in fetches]
dag.add_node(adder_chunk)
[dag.add_edge(c, adder_chunk) for c in fetches]
size_ctx = dict((c.key, (0, 0)) for c in fetches)
executor = Executor(storage=size_ctx, sync_provider_type=Executor.SyncProviderType.MOCK)
res = executor.execute_graph(dag, [adder_chunk.key], mock=True)
```

**Comment by wdkwyf** [comment]
@qinxuye 
In my computer, the difference of executing time is not very large.
Time used(n_parallel=8): 0.130967846 s
Time used(n_parallel=1): 0.014366305 s

**Comment by qinxuye** [comment]
> @qinxuye
> In my computer, the difference of executing time is not very large. (run these codes separately)
> Time used(n_parallel=8): 0.130967846 s
> Time used(n_parallel=1): 0.014366305 s

Pretty weird that it's indeed slow on my computer. I would investigate it later. Maybe it's due to some package in my environment.

**Comment by wdkwyf** [comment]
@wjsi @qinxuye 
Hi, for wjis's code, I find that it gets stuck in the while loop.
In execute function, ` len(self._submitted_op_keys)`(always 17000) can't exceed `len(self._op_key_to_ops)` (which is 17001)

**Comment by qinxuye** [comment]
> @wjsi @qinxuye
> Hi, for wjis's code, I find that it gets stuck in the while loop.
> In execute function, ` len(self._submitted_op_keys)`(always 17000) can't exceed `len(self._op_key_to_ops)` (which is 17001)

Thus it's a infinite loop, just like our expectation. Try to solve it?

**Comment by qinxuye** [comment]
The case is incorrect, the node in graph should be `TensorChunkData` instead of `TensorChunk`.

 
```

```
