### ISSUE TITLE
[BUG] Tensor converted from dataframe has wrong dtype

### ISSUE THREAD

**Issue by wdkwyf** [mars-project/mars#551]
**Describe the bug**
The tensor's dtype could be wrong when converted from dataframe using `to_tensor()`. 
**To Reproduce**
```
x = md.DataFrame({"x": [1,2,3], "y": [4., 5., 6.]})
y = x.to_tensor()
y.dtype # dtype('int64')
y.executed().dtype # dtype('float64')
```

**Expected behavior**
We should use [` find_common_type`](https://github.com/pandas-dev/pandas/blob/v0.24.2/pandas/core/dtypes/cast.py#L1072) to get the dtype of tensor as @sighingnow suggested.

**Comment by wjsi** [comment]
Seems already fixed somewhere?

```
import mars.dataframe as md
x = md.DataFrame({"x": [1,2,3], "y": [4., 5., 6.]})
y = x.to_tensor()
y.dtype
Out[5]: dtype('int64')
y.execute().dtype
Out[6]: dtype('int64')
```

under

```
numexpr                   2.7.0
numpy                     1.18.1
pandas                    1.0.0
```
