### ISSUE TITLE
[BUG] Two BUGs of distributed computing

### ISSUE THREAD

**Issue by anders0821** [mars-project/mars#552]
**Describe the bug**
BUG1: Summation of a small complex matrix -> Error: Changing the dtype of a 0d array is only supported if the itemsize is unchanged

BUG2: Operating a large tensor ->  different memory errors. I cannot operate a large tensor with shape [2,2,...,2]. The first element is one. Other elements are zeros. I cannot chunk it into 2^24 * 16B = 256MB to avoid the high peak memory cost of 2^30 * 16B = 16GB or 2^28 * 16B = 4GB. To simplify the bug, I whote this small demo

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Python 3.7.3
2. pymars 0.2.0b2
3. numpy 1.16.4, scipy 1.3.0 and protobuf 3.6.1
4. Errors of BUG1:
```
Error: Changing the dtype of a 0d array is only supported if the itemsize is unchanged
```
Errors of BUG2:
```
When method=1, N=30 -> ValueError: Cannot allocate size larger than the total capacity.
When method=1, N=28 -> mars.errors.SpillNotConfigured + failed With PinChunkFailed
When method=1, N=25 -> ValueError: Changing the dtype of a 0d array is only supported if the itemsize is unchanged
When method=2, N=30 -> ValueError: Changing the dtype of a 0d array is only supported if the itemsize is unchanged
When method=2, N=28 -> ValueError: Changing the dtype of a 0d array is only supported if the itemsize is unchanged
When method=2, N=25 -> ValueError: Changing the dtype of a 0d array is only supported if the itemsize is unchanged
```

5. Minimized code to reproduce the error. Code for BUG1:
```
a = mt.zeros([2, 2], dtype=mt.complex128)
a = mt.sum(a)
sess = new_session('http://127.0.0.1:7777')
print(a.execute(sess))
```
Code for BUG2:
```
method = 1  # switch two methods
N = 28
C = 24
chunk_size = (N - C) * [1] + C * [2]
if method == 1:
    statevector = mt.concatenate([mt.ones(1, mt.complex128), mt.zeros(2**N-1, mt.complex128)])
    statevector = mt.reshape(statevector, N * [2])
    statevector = statevector.rechunk(chunk_size)
    b = mt.sum(statevector)
else:
    statevector = mt.zeros(N * [2], dtype=mt.complex128, chunk_size=chunk_size)
    statevector.__setitem__((0,) * N, 1.0+0.0j)
    b = mt.sum(statevector)
sess = new_session('http://127.0.0.1:7777')
print(b.execute(sess))
```

**Expected behavior**
Code1 -> 0.0
Code2 -> 1.0

**Additional context**

**Comment by qinxuye** [comment]
Thank you for your report, could you please try to split this issue into one for two individual problems? So that we can solve the issues one by one.

**Comment by anders0821** [comment]
I notice that there may be two bugs: the complex converting and the memory overflow. I tried to split them. But according to the error message of bug 2, the second example may cause by both the complex converting and the memory overflow. To avoid confusion, I post two bugs together.
BTW, to reproduce memory overflow problem, a larger N should be used on a computer with larger memory.


发件人: Xuye (Chris) Qin <notifications@github.com>
发送时间: 2019年7月17日 21:33
收件人: mars-project/mars <mars@noreply.github.com>
抄送: Wenyun Sun <anders0821@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [mars-project/mars] [BUG] Two BUGs of distributed computing (#552)


Thank you for your report, could you please try to split this issue into one for two individual problems? So that we can solve the issues one by one.
