### ISSUE TITLE
Provide a smarter fusion strategy

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#597]
As described in #593, we need more rules to fuse more nodes when build fine-grained graph, it is a key step to enhance Mars optimizer, to start with, we can fuse diamond and inverted Y-shape in graph first.

**Comment by wdkwyf** [comment]
hi, @hekaisheng , there are fusion strategy in two places: one is `mars/fuse.pyx` which is used to generate `TensorFuseChunk`. The other is to generate a specified fuse chunk such as `TensorCpFuseChunk` or `TensorNeFuseChunk`. I wonder which one should I add this smarter fusion strategy. I think it shoule be the` fuse.pyx` one. Is that true？

**Comment by hekaisheng** [comment]
> hi, @hekaisheng , there are fusion strategy in two places: one is `mars/fuse.pyx` which is used to generate `TensorFuseChunk`. The other is to generate a specified fuse chunk such as `TensorCpFuseChunk` or `TensorNeFuseChunk`. I wonder which one should I add this smarter fusion strategy. I think it shoule be the` fuse.pyx` one. Is that true？

Yes, the logic of fusing fine-grained graph is in `fuse.pyx`, the fusion strategy concerns about the structure of graph and need not to know which operand the node represents.

**Comment by qinxuye** [comment]
This issue is staled, replaced by #2435 .
