### ISSUE TITLE
Support fetch tensor/dataframe using only the tileable keys

### ISSUE THREAD

**Issue by sighingnow** [mars-project/mars#608]
**Is your feature request related to a problem? Please describe.**

After #605, we can support the web session and local cluster session to fetch tensor/dataframe directly using the tileable keys.

**Describe the solution you'd like**

+ We first check if there are any GraphActor that contains in tileable, (the SessionActor already has such mapping)
+ When the key does not exist, raise an Exception.
+ For web session, return 404

**Describe alternatives you've considered**

**Additional context**

PR is coming.

**Comment by qinxuye** [comment]
`TileableData.key` is for private usage, at least for now. How about add the `name` property to `TileableData` just like `MutableTensorData`, so that we can get a tensor or DataFrame by giving a name.

Difference is that the name for `tensor` and `DataFrame` is optional, and we should ignore `name` when calculating `key`.

**Comment by qinxuye** [comment]
Thus `mt.tensor(name='a')` and `md.DataFrame(name='a')` can be used to get a tensor and DataFrame.

**Comment by sighingnow** [comment]
I don't think that adding `.name` to `Tensor` and `DataFrame` will benefit mars and potential users of mars. I think adding `.name` is bad, and makes things be _in a mess_. It will make things become more complicated and I think the `.name` property will cause a lot of confusion to users.

At the mars side, we might need to keep things as simple as possible, here the `simple` means consistent with numpy and pandas. That would make mars easier to be accepted by board users.

As for the feature requested in this proposal, I think we could just add some "hacks" to the `fetch` code path, like adding a _debugging_ api. And we might even don't need to advertise this _feature_ in the documentation.

**Comment by qinxuye** [comment]
> I don't think that adding `.name` to `Tensor` and `DataFrame` will benefit mars and potential users of mars. I think adding `.name` is bad, and makes things be _in a mess_. It will make things become more complicated and I think the `.name` property will cause a lot of confusion to users.
> 
> At the mars side, we might need to keep things as simple as possible, here the `simple` means consistent with numpy and pandas. That would make mars easier to be accepted by board users.
> 

Fair enough, I agree with this point, we should keep consistent as much as we can.

> As for the feature requested in this proposal, I think we could just add some "hacks" to the `fetch` code path, like adding a _debugging_ api. And we might even don't need to advertise this _feature_ in the documentation.

OK, if users call `execute` or `fetch`, we can do the check if it's executed before, it's transparent to users that they need not sense about what `key` is, if we can do that, I think it's workable.

**Comment by qinxuye** [comment]
Close with #693 .
