### ISSUE TITLE
[BUG] infer_index_value is wrong

### ISSUE THREAD

**Issue by sighingnow** [mars-project/mars#621]
**Describe the bug**

We have implemented `infer_index_value` as follows, noticing the `out_index = operator(left_index, right_index)` part, it doesn't make any sence to perform `operator` on `index_value`, since operators like `+-*/` are _element-wise_ on `Index` of pandas.

A trivial example to trigger the problem:

```python
df1 = pd.DataFrame(np.arange(10).reshape(5, 2), index=range(5))
df2 = pd.DataFrame(np.arange(10).reshape(5, 2), index=np.arange(5))

x = add(from_pandas(df1), from_pandas(df2))
x.tiles()
```

https://github.com/mars-project/mars/blob/e6594f0b9232b71ac3e6860ed6ca56a72a16f308/mars/dataframe/arithmetic/utils.py#L33-L52

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and protobuf
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Expected behavior**

Infer the correct value for `index_value`.

**Additional context**

**Comment by hekaisheng** [comment]
This function infers out index type, I have fixed this issue in #624 , you can check it in that PR.
