### ISSUE TITLE
Support selecting out lower-dimensional slices with [] for DataFrame and series

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#625]
**Is your feature request related to a problem? Please describe.**

Support basic indexing for DataFrame.

Object Type | Selection | Return Value Type
-- | -- | --
Series | series[label] | scalar value
DataFrame | frame[colname] | Series corresponding to colname

**Comment by sighingnow** [comment]
PR #638 implements fetching dataframe slice by `DataFrame.iloc`, which may be related to the `DataFrame` part of this issue.
