### ISSUE TITLE
Test tensor execution in distributed mode

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#71]
**Is your feature request related to a problem? Please describe.**
Currently, our expressions test cases all run by thread-based executor, however the behavior changes when running in cluster, only a few cases in `test_api` and `test_main` works for end to end.

Several issues(#19  #64  #8 ) are related to this, maybe we need some tests to cover them in the future.

**Describe the solution you'd like**
At least, we can add cases in `testGraphActor` to test `GraphActor` with different input tensors.

**Comment by chineking** [comment]
If most failure is due to the serialization, maybe we need to enhance the tests in tensor/expressions.

The e2e tests is quite heavy, I think we only need to test on some special and corner cases.

**Comment by wjsi** [comment]
We may test under a mimic setting for the distributed cases in an actor-free environment. That is, 

1. Serialize / deserialize the tensor graph;
2. Tile with the same code as ``GraphActor`` used;
3. Extract operands by ``get_executable_operand_dag``;
4. Execute operands one by one.

**Comment by qinxuye** [comment]
This issue would be replaced by #267 , close first.
