### ISSUE TITLE
Implement `numpy.random.shuffle` and `numpy.random.permutation`

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#729]
**Is your feature request related to a problem? Please describe.**

As `shuffle` and `permutation` are used to reshuffle data before training in deep learning or some stuff, we can introduce the API to Mars.

**Describe the solution you'd like**

We can implement them with shuffle, in the shuffle map, we generate a random 1-d array in which each element indicates which downstream should sent to, and in the shuffle reduce, random shuffle the data.

**Comment by sighingnow** [comment]
We can simply implement these two methods via a fancy index on a `Tensor` value since fancy index on tensor value is already implemented using shuffle.

**Comment by qinxuye** [comment]
> We can simply implement these two methods via a fancy index on a `Tensor` value since fancy index on tensor value is already implemented using shuffle.

Maybe it's a bit hard to generate a index tensor which contains non-repeat numbers?
