### ISSUE TITLE
[ENH] RPC calls in data transfer can be simplified

### ISSUE THREAD

**Issue by wjsi** [mars-project/mars#730]
In ``transfer.py`` a data transfer procedure is initialized in 4 RPC calls:

1. A ``get_hash_slot`` is sent to obtain a new receiver slot from the remote end
2. A ``check_status`` query is sent to check if data already sent to the target
3. A ``create_data_writer`` is sent to initialize the receiver
4. A ``register_finish_callback`` is sent to create a callback to listen when the transfer finishes

However, all these requests can be merged into one single request to reduce latency esp. when data packages are small.

Further more, ``receive_data_part`` and ``finish_receive`` can also be merged, and a small chunk may only cost 2 RPC calls.

**Comment by qinxuye** [comment]
Fixed by #736 .
