### ISSUE TITLE
Implement airy functions

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#750]
Implement airy functions including `airy`, `airye`, `ai_zeros`, `bi_zeros`, `itairy`.
list in https://docs.scipy.org/doc/scipy/reference/special.html#airy-functions.

**Comment by hxri** [comment]
I this done yet?

If not I would like to contribute to this.

**Comment by qinxuye** [comment]
> I this done yet?
> 
> If not I would like to contribute to this.

No, it's still open, welcome to contribute, thanks in advance.

**Comment by kunalgaur7983** [comment]
is this issue opened??
i would love to contribute

**Comment by wjsi** [comment]
> is this issue opened?? i would love to contribute

This issue is still open. We close #2612 as it does not meet our need and the contributor did not respond in time. Note that special functions with multiple outputs are different from those with only one output. You may implement #751 or #757 first if you do not know how to deal with this issue.
