### ISSUE TITLE
Support error function and fresnel integrals 

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#757]
Support error function and fresnel integrals in https://docs.scipy.org/doc/scipy/reference/special.html#error-function-and-fresnel-integrals, those are not universal functions may not need to be supported.

**Comment by M-S-10** [comment]
@hekaisheng Could you please guide me on this?

**Comment by hekaisheng** [comment]
> @hekaisheng Could you please guide me on this?

Here is the guidelines, https://docs.pymars.org/en/latest/development/contributing.html .
