### ISSUE TITLE
raise RuntimeError('No GPU found for execution') RuntimeError: No GPU found for execution

### ISSUE THREAD

**Issue by zzqiuzz** [mars-project/mars#844]
`a = mt.random.rand(1000, 2000, gpu=True)` release error No GPU found for execution.And how to assign tensors to a specified gpu ?

**Comment by qinxuye** [comment]
Currently Mars only supports Nvidia GPU, and Mars detect GPU via [nvml](https://developer.nvidia.com/nvidia-management-library-nvml), did you run your code in the right environment?

**Comment by zzqiuzz** [comment]
@qinxuye  Yes! Command `nvidia-smi` actually shows 4 Titan xp GPUs .Mars was installed in Anaconda3 via `pip install pymars`,however,it just released error overhead.

**Comment by qinxuye** [comment]
Could you please pate the full error message please? So that we can track what's going on exactly.

**Comment by zzqiuzz** [comment]
@qinxuye 
` import mars.tensor as mt`
` a = mt.random.rand(1000, 2000, gpu=True)`
 `a.execute()`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhengzhe/anaconda3/lib/python3.7/site-packages/mars/tensor/core.py", line 452, in execute
    return self._data.execute(session, **kw)
  File "/home/zhengzhe/anaconda3/lib/python3.7/site-packages/mars/core.py", line 584, in execute
    return session.run(self, **kw)
  File "/home/zhengzhe/anaconda3/lib/python3.7/site-packages/mars/session.py", line 166, in run
    result = self._sess.run(*tileables, **kw)
  File "/home/zhengzhe/anaconda3/lib/python3.7/site-packages/mars/session.py", line 72, in run
    raise RuntimeError('No GPU found for execution')
RuntimeError: No GPU found for execution

**Comment by qinxuye** [comment]
I guess maybe it's due to absence of `psutil`.

Try:

`pip install psutil` or `conda install psutil`

to see if it can work.

**Comment by qinxuye** [comment]
And remember that `cupy` is also required for GPU computing, try `pip install cupy-cudaxxx`, xxx is the version of cuda, for instance `pip install cupy-cuda101` for cuda 10.1.

**Comment by qinxuye** [comment]
Hey, @zzqiuzz , have you solved your issue yet?

**Comment by zzqiuzz** [comment]
@qinxuye Sorry , it didn't work.Error the same .

**Comment by qinxuye** [comment]
> @qinxuye Sorry , it didn't work.Error the same .

 `psutil` has been installed, right? If so, try the code below, could you tell me what's the result?

```python
from mars.resource import cuda_count
print(cuda_count())
```

**Comment by zzqiuzz** [comment]
both `psutil ` and ` cupy-cuda90` have been installed.
After trying the code, shown:
> from mars.resource import cuda_count
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'cuda_count' from 'mars.resource' (/home/zhengzhe/anaconda3/lib/python3.7/site-packages/mars/resource.py)

**Comment by qinxuye** [comment]
Try install Mars via:

`pip install --pre pymars`

Seems `resource.py` was not correctly backported on our stable branch. Try our dev branch, if it can work, will fix it soon.

**Comment by zzqiuzz** [comment]
@qinxuye  3ku very much.Now it's OK。

**Comment by qinxuye** [comment]
Thank you for your report. GPU related code has been backported, for the upcoming 0.2.4 version it will work as well.

I will close this issue first, feel free to reopen if new issue arises.

**Comment by ShiLijuan1997** [comment]
i have the same issue, but it seems you use the pip install --pre pymars to resolve this problem, right? but it didn't work for me, have you do something else ?
