### ISSUE TITLE
How to use GPU for calculation?

### ISSUE THREAD

**Issue by sc1101** [mars-project/mars#945]
Hello!
When I run the code：
`import mars.tensor as mt

a = mt.random.rand(1000, 2000, gpu=True)

b = (a + 1).sum(axis=1).execute()
`
，It threw RuntimeError: No GPU found for execution，But I don't know what to do. My graphics card is GTX760 and pycuda has been installed. Can you help me?

In addition, do you have a detailed tutorial on Mars in Chinese?

Thank you very much!

**Comment by qinxuye** [comment]
Could you please translate your issue into English please to convenient others, Thank you so much.

**Comment by qinxuye** [comment]
Seems duplicated with #844.

Try to install new version of Mars( newest stable version: 0.3.0) and see if problem solved.

`pip install --upgrade pymars`

Chinese docs is available at: https://docs.mars-project.io/zh_CN/latest/
We are still working on enriching our docs, if any problem found, welcome to open new Issues as well.

**Comment by sc1101** [comment]
> Could you please translate your issue into English to convenient others, Thank you so much.

OK, I translated my issue. In addition, should I install the "cuda" software at first? If so, which version should I download?

![image](https://user-images.githubusercontent.com/60003504/72710194-811a9d80-3ba1-11ea-8024-7e43b209184e.png)

**Comment by sc1101** [comment]
> Seems duplicated with #844.
> 
> Try to install new version of Mars( newest stable version: 0.3.0) and see if problem solved.
> 
> `pip install --upgrade pymars`
> 
> Chinese docs is available at: https://docs.mars-project.io/zh_CN/latest/
> We are still working on enriching our docs, if any problem found, welcome to open new Issues as well.

My mars version is 0.3.0.
![image](https://user-images.githubusercontent.com/60003504/72710299-c048ee80-3ba1-11ea-9f11-30573bf7a039.png)

**Comment by qinxuye** [comment]
@sc1101 You need cuda driver as well as cupy, for example if your cuda version is 10.

try install `pip install cupy-cuda100`.

**Comment by sc1101** [comment]
> @sc1101 You need cuda driver as well as cupy, for example if your cuda version is 10.
> 
> try install `pip install cupy-cuda100`.

Thanks a lot, I am trying now and will feedback soon.

**Comment by sc1101** [comment]
Thank you very much! I think I have solved the problem.

**Comment by sc1101** [comment]
Hello, sorry for bothering you again. In these two days I have tried to install CUDA for many different versions and installed the cupy-cuda100. But it still can't work. 

My graphics card is "GTX 760". At first I thought it were CUDA's problem, and I were believed that I cound fix it, but I failed at last. I tried to install CUDA 8.0、CUDA 9.2、CUDA10.0、CUDA10.2, and updated pymars for many times, it still throws "RuntimeError: No GPU found for execution". 

What should I do? Can you order some team members to give me a long-distance aid? Thank you very much.

**Comment by qinxuye** [comment]
Cupy is required for Mars to perform computation on GPU. 

I guess you'd better fix your cuda version to 10.0 or 10.1.

For cuda 10.0, install pre-compiled cupy via `pip install cupy-cuda100`, 
For cuda 10.1, install via `pip install cupy-cuda101`. 

The cupy package should matches well with version of cuda.

You can refer to the installation guide of cupy: https://docs-cupy.chainer.org/en/stable/install.html

**Comment by wjsi** [comment]
Close as no responses for a long time.
