### ISSUE TITLE
[BUG] count_nonzero produces unexpected output for non-boolean tensor

### ISSUE THREAD

**Issue by jcmgray** [mars-project/mars#999]
**Describe the bug**
``count_nonzero`` only produces the expected output for boolean arrays and integer arrays of 1s and 0s.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. *Python:* 3.7
2. *The version of Mars you use:* github master
3. *Versions of crucial packages, such as numpy, scipy and protobuf:* 1.18.1, 1.4.1, 3.11.2

**Expected behavior**
`count_nonzero` should count the number of non-zero values of any type which are not, 0, 0.0 or False etc.

```python
import numpy as np
import mars.tensor as mt
```

The following two work as expected:
```python
values = [False, True, False, True]
print(np.count_nonzero(np.array(values)))
print(mt.count_nonzero(mt.tensor(values)).execute())
# 2
# 2

values = [0, 1, 0, 1]
print(np.count_nonzero(np.array(values)))
print(mt.count_nonzero(mt.tensor(values)).execute())
# 2
# 2
```
but then we run into problems:
```python
values = [0, 2, 0, 3]
print(np.count_nonzero(np.array(values)))
print(mt.count_nonzero(mt.tensor(values)).execute())
# 2
# 5

values = [0.0, 0.2, 0.0, 0.3]
print(np.count_nonzero(np.array(values)))
print(mt.count_nonzero(mt.tensor(values)).execute())
# 2
# 0.5
```
It seems like `mars` is just doing a sum.

**Comment by qinxuye** [comment]
Thank you for your report, we will try to solve it as soon as possible.
